hmcts/sptribs-case-api

Jenkinsfile_CNP
=> Fix MetricsPublisher constructor

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/ST-415
```
[ ] Yes
[x ] No
```
=> ST-415-Respondent to be fixed as CICA email address

src/main/java/uk/gov/hmcts/divorce/ciccase/model/State.java, src/test/java/uk/gov/hmcts/divorce/ciccase/model/StateTest.java
https://tools.hmcts.net/jira/browse/ST-412
```
[ ] Yes
[ x] No
```
=> ST-412-Update Case API State Transition Table

src/main/java/uk/gov/hmcts/divorce/ciccase/CriminalInjuriesCompensation.java, src/main/java/uk/gov/hmcts/divorce/ciccase/model/UserRole.java, src/main/java/uk/gov/hmcts/divorce/ciccase/model/UserRoleCIC.java, src/main/java/uk/gov/hmcts/divorce/ciccase/model/UserRoleCS.java, src/main/java/uk/gov/hmcts/divorce/ciccase/model/UserRoleMH.java, src/main/java/uk/gov/hmcts/divorce/ciccase/model/UserRolePHL.java, src/main/java/uk/gov/hmcts/divorce/ciccase/model/UserRoleSEND.java, src/main/java/uk/gov/hmcts/divorce/ciccase/model/access/AosAccess.java, src/main/java/uk/gov/hmcts/divorce/ciccase/model/access/Applicant2Access.java, src/main/java/uk/gov/hmcts/divorce/ciccase/model/access/Applicant2ReadAccess.java, src/main/java/uk/gov/hmcts/divorce/ciccase/model/access/DefaultStateAccess.java, src/main/java/uk/gov/hmcts/divorce/ciccase/model/access/DefaultStateAccessExcludingCAA.java, src/main/java/uk/gov/hmcts/divorce/ciccase/model/access/OrganisationPolicyAccess.java, src/main/java/uk/gov/hmcts/divorce/ciccase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessService.java, src/test/java/uk/gov/hmcts/divorce/ciccase/model/access/AosAccessTest.java, src/test/java/uk/gov/hmcts/divorce/ciccase/model/access/Applicant2AccessTest.java, src/test/java/uk/gov/hmcts/divorce/ciccase/model/access/Applicant2ReadAccessTest.java, src/test/java/uk/gov/hmcts/divorce/ciccase/model/access/DefaultStateAccessExcludingCAATest.java, src/test/java/uk/gov/hmcts/divorce/ciccase/model/access/DefaultStateAccessTest.java, src/test/java/uk/gov/hmcts/divorce/ciccase/model/access/OrganisationPolicyAccessTest.java
https://tools.hmcts.net/jira/browse/ST-413
```
[ ] Yes
[ x] No
```
=> ST-314-roles permission classes has been defined

src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerAddNoteIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerCreateGeneralLetterIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/common/config/SwaggerPublisherIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/common/config/interceptors/RequestInterceptorIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/document/content/GeneralOrderTemplateContentIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/endpoint/ValidationControllerIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorConfirmServiceIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessServiceIT.java, src/integrationTest/java/uk/gov/hmcts/divorce/testutil/CaseDataWireMock.java, src/integrationTest/java/uk/gov/hmcts/divorce/testutil/DocAssemblyWireMock.java, src/integrationTest/java/uk/gov/hmcts/divorce/testutil/DocManagementStoreWireMock.java, src/integrationTest/java/uk/gov/hmcts/divorce/testutil/FeesWireMock.java, src/integrationTest/java/uk/gov/hmcts/divorce/testutil/IdamWireMock.java, src/integrationTest/java/uk/gov/hmcts/divorce/testutil/PrdOrganisationWireMock.java, src/integrationTest/java/uk/gov/hmcts/divorce/testutil/SendLetterWireMock.java, src/integrationTest/resources/application.yaml
https://tools.hmcts.net/jira/browse/ST-370
integration tests
```
[ ] Yes
[ x] No
```
=> ST-370-integration-tests

src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerAddNoteIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerCreateGeneralLetterIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/common/config/SwaggerPublisherIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/common/config/interceptors/RequestInterceptorIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/document/content/GeneralOrderTemplateContentIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/endpoint/ValidationControllerIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/solicitor/SolicitorConfirmServiceIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/solicitor/service/CcdAccessServiceIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/testutil/CaseDataWireMock.java, src/integrationTest/java/uk/gov/hmcts/sptribs/testutil/DocAssemblyWireMock.java, src/integrationTest/java/uk/gov/hmcts/sptribs/testutil/DocManagementStoreWireMock.java, src/integrationTest/java/uk/gov/hmcts/sptribs/testutil/FeesWireMock.java, src/integrationTest/java/uk/gov/hmcts/sptribs/testutil/IdamWireMock.java, src/integrationTest/java/uk/gov/hmcts/sptribs/testutil/PrdOrganisationWireMock.java, src/integrationTest/java/uk/gov/hmcts/sptribs/testutil/SendLetterWireMock.java
https://tools.hmcts.net/jira/browse/ST-492
Refactoring newly added integration tests from divorce to sptribs
```
[ ] Yes
[ x] No
```
=> ST-492 Refactoring integration tests from divorce to sptribs

src/cftlib/java/uk/gov/hmcts/sptribs/cftlib/CftLibConfig.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerAddNoteIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/endpoint/ValidationControllerIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/testutil/DocAssemblyWireMock.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestConstants.java
https://tools.hmcts.net/jira/browse/ST-499
```
[ ] Yes
[ X] No
```
=> ST-499-TECH DEBT: Add the literal to TestConstants

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseCategory.java
https://tools.hmcts.net/jira/browse/ST-503
```
[ ] Yes
[ ] No
```
=> isAssessment Method Removed

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/State.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/model/StateTest.java
https://tools.hmcts.net/jira/browse/ST-411
```
[ ] Yes
[ x] No
```
=> ST-411-Upgrade Case API Dependencies

Jenkinsfile_CNP, README.md, bin/add-cron.sh, bin/get-user-id-by-email.sh, bin/patch-cases-in-ccd.sh, build.gradle, charts/sptribs-case-api/Chart.yaml, charts/sptribs-case-api/values.preview.template.yaml, charts/sptribs-case-api/values.yaml, lib/applicationinsights.json, package.json, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/sptribs/document/print/BulkPrintService.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/ST-575
```
[ ] Yes
[ x] No
```
=> ST-575-Remove mention of NFDIV

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/EditApplicantDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/EditCaseCategorisationDetails.java
https://tools.hmcts.net/jira/browse/ST-421
Edit a category & sub category
```
[ ] Yes
[x] No
```
=> change for ST-421

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCase.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/sptribs/common/event/CreateTestCase.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/SubjectDetails.java
https://tools.hmcts.net/jira/browse/ST-344
Edit Subject details
```
[ ] Yes
[x] No
```
=> change for ST-344

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java
https://tools.hmcts.net/jira/browse/ST-334
Prefixing party name i.e. Subject/Applicant/Representative to Labels to display on Summary page
```
[ ] Yes
[x ] No
```
=> ST-334: Prefix party name to label

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCase.java, src/main/java/uk/gov/hmcts/sptribs/common/event/CreateTestCase.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/ApplicantDetails.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/RepresentativeDetails.java
https://tools.hmcts.net/jira/browse/ST-346
Edit Representation details
```
[ ] Yes
[x] No
```
=> change for ST-346

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCase.java
https://tools.hmcts.net/jira/browse/ST-351
Case updated confirmation page
```
[ ] Yes
[x] No
```
=> change for ST-351

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStayTheCase.java
https://tools.hmcts.net/jira/browse/ST-479
summary page after stay
```
[ ] Yes
[x ] No
```
=> Stay summary page/ check answers

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRemoveStay.java
https://tools.hmcts.net/jira/browse/ST-480
```
[ ] Yes
[ ] No
```
=> ST-480 Remove Stay Page

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRemoveStay.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/RemoveCaseStay.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/StayRemoveReason.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java
https://tools.hmcts.net/jira/browse/ST-481
```
[ ] Yes
[x] No
```
=> ST-481 Remove Stay Reason

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRemoveStay.java
https://tools.hmcts.net/jira/browse/ST-482
```
[ ] Yes
[ ] No
```
=> ST-482 Remove Stay Confirmation

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCase.java
https://tools.hmcts.net/jira/browse/ST-459
Added before start message for Link case
```
[ ] Yes
[x ] No
```
=> ST-459: Added before start message to Link case

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRemoveStay.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseRemoveStayTest.java
https://tools.hmcts.net/jira/browse/ST-489
```
[ ] Yes
[x ] No
```
=> ST-489 Remove Stay Check Answers

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRemoveStay.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStayTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/RemoveCaseStay.java
https://tools.hmcts.net/jira/browse/ST-481
```
[ ] Yes
[ ] No
```
=> ST-481 Labels changed

src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/ST-341
Added Case status to Summary tab
```
[ ] Yes
[x ] No
```
=> ST-341: Added Case status to Summary tab

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseCategory.java
https://tools.hmcts.net/jira/browse/ST-636
```
[ ] Yes
[ x] No
```
=> ST-636 Case Category Typo Fixed

src/main/java/uk/gov/hmcts/sptribs/common/event/page/FurtherDetails.java
https://tools.hmcts.net/jira/browse/ST-348
Change to display question in further details
```
[ ] Yes
[x ] No
```
=> ST-348: Change to display question in further details

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRemoveStay.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStayTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/RemoveStatNextState.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/RemoveStay.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/NextState.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseRemoveStayTest.java
https://tools.hmcts.net/jira/browse/ST-627
```
[ ] Yes
[ ] No
```
=> ST-627 Remove Stay Next state page

README.md
https://tools.hmcts.net/jira/browse/ST-505
```
[ ] Yes
[ ] No
```
=> ST-505 Readme page

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseFlag.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagAdditionalInfo.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseFlag.java
=> ST-443 Additional Comments Page

src/test/java/uk/gov/hmcts/sptribs/ciccase/model/StateTest.java
=> for jenkins test

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseFlag.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagLevel.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseFlag.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/FlagLevel.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/FlagParty.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java
https://tools.hmcts.net/jira/browse/ST-441
```
[ ] Yes
[x] No
```
=> ST-441 Selecting Flag Level

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseFlag.java
=> ST-443 Regex Changed

build.gradle, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseFlag.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagLevel.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagTypePage.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseFlag.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/common/model/Status.java, src/main/java/uk/gov/hmcts/sptribs/systemupdate/service/CcdSearchService.java
https://tools.hmcts.net/jira/browse/ST-442
```
[ ] Yes
[x] No
```
=> ST-442 Select Flag Type

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerManageCaseFlag.java
https://tools.hmcts.net/jira/browse/ST-447
```
[ ] Yes
[x] No
```
=> ST-447 Manage a Flag page

Jenkinsfile_CNP, charts/sptribs-case-api/Chart.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/ST-670
```
[ ] Yes
[x ] No
```
=> ST-670-supressions-and-helmchart-update

build.gradle, charts/sptribs-case-api/Chart.yaml, charts/sptribs-case-api/values.preview.template.yaml, charts/sptribs-case-api/values.yaml
https://tools.hmcts.net/jira/browse/ST-670
```
[ ] Yes
[x ] No
```
=> ST-670-sonar-exclude

build.gradle, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/ApplicantPrayer.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/validation/ValidationUtil.java, src/main/java/uk/gov/hmcts/sptribs/document/content/provider/ApplicantTemplateDataProvider.java, src/main/java/uk/gov/hmcts/sptribs/systemupdate/service/task/GenerateConditionalOrderPronouncedDocument.java
https://tools.hmcts.net/jira/browse/ST-670
```
[ ] Yes
[ x] No
```
=> ST-670-package-updates-to-latest

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseFlag.java
=> ST-443 clean fields after submit

charts/sptribs-case-api/values.preview.template.yaml, src/main/java/uk/gov/hmcts/sptribs/common/ccd/HighLevelDataSetupApp.java
https://tools.hmcts.net/jira/browse/DTSPO-10753
https://tools.hmcts.net/jira/browse/ST-583
```
[ ] Yes
[x ] No
```
=> ST-670-fix-for-befta

src/main/java/uk/gov/hmcts/sptribs/common/service/task/SendSubmissionNotifications.java
=> ST-651: Fixed PMD issue

src/main/java/uk/gov/hmcts/sptribs/caseworker/service/task/SendApplicationIssueNotifications.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/State.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/service/task/SendApplicationIssueNotificationsTest.java
=> ST-651: Removed 23 more redundant states and related code

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseFlag.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseFlagDisplay.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java
https://tools.hmcts.net/jira/browse/ST-490
```
[ ] Yes
[x] No
```
=> ST-490 Summary page for flags

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCancelHearingFlag.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/HearingCancellationReasonSelect.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/HearingDateSelect.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CancelHearing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/HearingCancellationReason.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java
https://tools.hmcts.net/jira/browse/ST-710
```
[ ] Yes
[x] No
```
=> ST-710 Cancel Hearing select reason

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCancelHearingFlag.java
https://tools.hmcts.net/jira/browse/ST-713
```
[ ] Yes
[x] No
```
=> ST-713 Cancel Hearing Check Answers

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/TestStateChange.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReinstateWarning.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/State.java
https://tools.hmcts.net/jira/browse/ST-639
```
[ ] Yes
[x] No
```
=> ST-639 Reinstate case

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/TestStateChange.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReinstateReasonSelect.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseReinstate.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/ReinstateReason.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java
https://tools.hmcts.net/jira/browse/ST-771
```
[ ] Yes
[x] No
```
=> ST-771 Reinstate Reason Page

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/RecordListing.java
https://tools.hmcts.net/jira/browse/ST-666
Added Remote Hearing Information page
```
[ ] Yes
[x ] No
```
=> ST-666: Added Remote Hearing Information page - Record listing

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/TestStateChange.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseReinstate.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/ReinstateReason.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java
https://tools.hmcts.net/jira/browse/ST-771
```
[ ] Yes
[X] No
```
=> ST-771 Fixed QA comments

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReinstateUploadDocuments.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java
https://tools.hmcts.net/jira/browse/ST-780
```
[ ] Yes
[x] No
```
=> ST-780 Reinstate Upload Documents

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseFlag.java
https://tools.hmcts.net/jira/browse/ST-822
```
[ ] Yes
[x] No
```
=> ST-822 PMD error fix

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/RecordListing.java
https://tools.hmcts.net/jira/browse/ST-667
Added Other Information - Record listing
```
[ ] Yes
[x ] No
```
=> Feat/st 667: Added Other Information - Record listing

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCase.java
https://tools.hmcts.net/jira/browse/ST-782
```
[ ] Yes
[x] No
```
=> ST-782 Reinstate Case Check Answers

.gitignore, infrastructure/appinsights.tf
ST-806
Add content type and tags to secret
```
[ ] Yes
[ x ] No
```
=> ST-806 - Add content type and tags to secret

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReinstateWarning.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java
https://tools.hmcts.net/jira/browse/ST-639
```
[ ] Yes
[x] No
```
=> ST-639 Message Fixes

infrastructure/appinsights.tf
https://tools.hmcts.net/jira/browse/ST-385
```
[ ] Yes
[ ] No
```
=> ST-385- build problems

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/ST-819
```
[ ] Yes
[ ] No
```
=> ST-819-build problems

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/util/AccessCodeGeneratorTest.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/util/SolicitorAddressPopulatorTest.java
=> ST-820: Added JUnit tests for ciccase.util package

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStayTheCase.java
=> ST-804: Changed to allow add stay for case-stayed as well

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReinstateUploadDocuments.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java
[782
](https://tools.hmcts.net/jira/browse/ST-782)
```
[ ] Yes
[x] No
```
=> ST-782 Message changed

src/main/java/uk/gov/hmcts/sptribs/common/ccd/HighLevelDataSetupApp.java
https://tools.hmcts.net/jira/browse/ST-825
```
[ ] Yes
[ x] No
```
=> ST-825-override has been canceled

src/test/java/uk/gov/hmcts/sptribs/document/DraftApplicationRemovalServiceTest.java
=> ST-820: Added new JUnit tests

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCaseNotifyPartiesTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCaseTest.java
https://tools.hmcts.net/jira/browse/ST-783
```
[ ] Yes
[x] No
```
=> ST-783 Recored Created

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrderTest.java
https://tools.hmcts.net/jira/browse/ST-577
```
[ ] Yes
[x] No
```
=> ST-577 Send Order

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/ST-851
https://tools.hmcts.net/jira/browse/ST-850
```
[ ] Yes
[ ] No
```
=> ST-851-CVE supression

charts/sptribs-case-api/values.yaml, lib/applicationinsights.json
ST-853
remove unwanted secret from chart
```
[ ] Yes
[ x ] No
```
=> ST-853 - remove unwanted secret from chart

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCaseTest.java
https://tools.hmcts.net/jira/browse/ST-783
```
[ ] Yes
[x] No
```
=> ST-783 Message fixed

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/ST-834
```
[ ] Yes
[ ] No
```
=> ST-834-override-prod-secrets-from-aat

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/UploadOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/OrderIssuingType.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/SendOrder.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java
https://tools.hmcts.net/jira/browse/ST-601
```
[ ] Yes
[x] No
```
=> ST-601 Upload order from your computer

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/OrderDueDates.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/DateModel.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/SendOrder.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrderTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStayTheCaseTest.java
https://tools.hmcts.net/jira/browse/ST-581
```
[ ] Yes
[x] No
```
=> ST-581 Send Order Add Due Date

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/HearingNoticeOption.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/RecordListing.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/HearingDate.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListingTest.java
=> Feat/st 672: Record Listing - Create Hearing Notice

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReinstateNotifyParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/SendOrderNotifyParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/SendOrderOrderDueDates.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/SendOrderOrderIssuingSelect.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/SendOrderUploadOrder.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrderTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReinstateCaseNotifyPartiesTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/page/SendOrderNotifyPartiesTest.java
https://tools.hmcts.net/jira/browse/ST-584
```
[ ] Yes
[x] No
```
=> ST-584 Send Order Select Recipients

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/RecordListing.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/RecordListingTemplate.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListingTest.java
https://tools.hmcts.net/jira/browse/ST-673
Record listing - Select template
```
[ ] Yes
[x ] No
```
=> Feat/st 673: Record listing - Select template

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/SendOrderAddDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/SendOrder.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrderTest.java
https://tools.hmcts.net/jira/browse/ST-580
```
[ ] Yes
[x] No
```
=> ST-580 Select draft order

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/SendOrderAddDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/SendOrderUploadOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/OrderIssuingType.java
https://tools.hmcts.net/jira/browse/ST-593
```
[ ] Yes
[x] No
```
=> ST-593 Send orders summary

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/DateModel.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/SendOrder.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrderTest.java
https://tools.hmcts.net/jira/browse/ST-581
```
[ ] Yes
[x] No
```
=> ST-581 Due Date information field

Jenkinsfile_CNP, bin/add-cron.sh, charts/sptribs-case-api/values.aat.template.yaml, charts/sptribs-case-api/values.preview.template.yaml, charts/sptribs-case-api/values.yaml, lib/applicationinsights.json, src/main/resources/application.yaml
DTSPO-11171
Correct secrets for App Insights
```
[ ] Yes
[ x ] No
```
=> Correct secrets for App Insights

src/main/resources/application.yaml
=> ST-582: reverted some deleted vars to keep structure with TO Do comments

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCaseTest.java
https://tools.hmcts.net/jira/browse/ST-783
```
[ ] Yes
[x] No
```
=> ST-783  conformation page

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueCaseTest.java
https://tools.hmcts.net/jira/browse/ST-640
```
[ ] Yes
[x] No
```
=> ST-640 Issue case

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateDraftOrder.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerDraftOrderTest.java
https://tools.hmcts.net/jira/browse/ST-580
```
[ ] Yes
[x] No
```
=> ST-580 multiple draft orders

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCase.java
https://tools.hmcts.net/jira/browse/ST-783
```
[ ] Yes
[x] No
```
=> ST-783 Message Rolled back

charts/sptribs-case-api/values.preview.template.yaml
Correct the alias' for preview app insight secrets in the charts.
```
[ ] Yes
[ x ] No
```
=> Add Correct Alias for App Insihgts

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtil.java
https://tools.hmcts.net/jira/browse/ST-595
```
[ ] Yes
[x] No
```
=> ST-595 Message font changed

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueCaseAdditionalDocument.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/AdditionalDocument.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseIssue.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueCaseTest.java
=> ST-645 Issue case add additional document

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, submission_error.patch
https://tools.hmcts.net/jira/browse/ST-595
```
[ ] Yes
[x] No
```
=> Feat/st 595 Message Changed

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrder.java
Developer a page for edit main contents for edit draft order.
```
[ ] Yes
[x] No
```
=> Created a main content editable page on edit draft order

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrder.java
###https://tools.hmcts.net/jira/browse/ST-572  ###
Changed the Edit draft order event message
```
[ ] Yes
[x] No
```
=> Created an edit draft order event message

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecision.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecisionTest.java
https://tools.hmcts.net/jira/browse/ST-751
```
[ ] Yes
[x] No
```
=> ST-751 Issue final decision journey start

src/main/java/uk/gov/hmcts/sptribs/common/event/page/ApplicantDetails.java
https://tools.hmcts.net/jira/browse/ST-916
```
[ ] Yes
[x] No
```
=> ST-916 Applicant email selection

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReinstateNotifyParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/SendOrderNotifyParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/CheckRequiredUtil.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagPartiesTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/CheckRequiredUtilTest.java
https://tools.hmcts.net/jira/browse/ST-917
```
[ ] Yes
[x] No
```
=> ST-917 Controls moved to Util

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueFinalDecisionNotice.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseIssueFinalDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/NoticeOption.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/RecordListing.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecisionTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListingTest.java
https://tools.hmcts.net/jira/browse/ST-760
Changes type in record listing
```
[x] Yes
[ ] No
```
=> ST-760 Issue Final Decision Notice option

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueCase.java
https://tools.hmcts.net/jira/browse/ST-655
```
[ ] Yes
[x] No
```
=> ST-655 Message fixed

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueCaseAdditionalDocument.java
=> ST-645 Page title fixed

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueFinalDecisionSelectTemplate.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseIssueFinalDecision.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/FinalDecisionTemplate.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecisionTest.java
https://tools.hmcts.net/jira/browse/ST-761
```
[ ] Yes
[x] No
```
=> ST-761 Select decision notice

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueFinalDecisionNotice.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueFinalDecisionSelectTemplate.java
https://tools.hmcts.net/jira/browse/ST-760
```
[ ] Yes
[x] No
```
=> ST-760 Message added

src/cftlib/java/uk/gov/hmcts/sptribs/cftlib/CftLibConfig.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/UserRole.java
https://tools.hmcts.net/jira/browse/ST-770
```
[ ] Yes
[ ] No
```
=> ST-770-refactoring for roles

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloseTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseWarning.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CloseCase.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CloseCaseTest.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestDataHelper.java
https://tools.hmcts.net/jira/browse/ST-768
Ability to close case when in draft state
```
[ ] Yes
[X] No
```
=> ST 768 Close Case in Draft State

resources/bundle.yaml
https://tools.hmcts.net/jira/browse/ST-854
```
[ ] Yes
[x] No
```
=> ST-854 Bundle file

bin/add-cron.sh, charts/sptribs-case-api/values.aat.template.yaml, charts/sptribs-case-api/values.preview.template.yaml, charts/sptribs-case-api/values.yaml, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/common/config/NotificationsConfiguration.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/ST-791
Renamed Notify key to fix the issue
```
[ ] Yes
[x] No
```
=> Fix for Notification error

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerManageOrderDueDate.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/AmendOrderDueDates.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ManageSelectOrders.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/DateModel.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/Order.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/GetAmendDateAsCompleted.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/page/SendOrderAddDraftOrderTest.java
Created a check answers page
```
[ ] Yes
[x] No
```
=> Created Summary page

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCancelHearing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/RecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/service/HearingService.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtil.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/NotificationParties.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCancelHearingTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListingTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtilTest.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestConstants.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestDataHelper.java
https://tools.hmcts.net/jira/browse/ST-714
```
[ ] Yes
[x] No
```
=> ST-714 Cancel hearing conformation page

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueFinalDecisionNotice.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueFinalDecisionPreviewTemplate.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueFinalDecisionSelectTemplate.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseIssueFinalDecision.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/FinalDecisionTemplate.java, src/main/java/uk/gov/hmcts/sptribs/document/DocumentConstants.java, src/main/java/uk/gov/hmcts/sptribs/document/content/DocmosisTemplateConstants.java, src/main/java/uk/gov/hmcts/sptribs/document/content/FinalDecisionTemplateContent.java, src/main/java/uk/gov/hmcts/sptribs/document/model/DocAssemblyResponse.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecisionTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueFinalDecisionSelectTemplateTest.java, src/test/java/uk/gov/hmcts/sptribs/document/content/FinalDecisionTemplateContentTest.java
https://tools.hmcts.net/jira/browse/ST-762
```
[ ] Yes
[x] No
```
=> ST-762 Initial Commit

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrder.java
Created a check answer page for contact parties
```
[ ] Yes
[x] No
```
=> Created check answers page

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/HearingCancellationReason.java
https://tools.hmcts.net/jira/browse/ST-710
```
[ ] Yes
[x] No
```
=> ST-710 Order changed

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerIssueDecision.java
=> Issue Decision choice

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CancelHearing.java
https://tools.hmcts.net/jira/browse/ST-710
```
[ ] Yes
[x] No
```
=> ST-710 Cancel Reason Radio button

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCancelHearing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/RecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtil.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCancelHearingTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListingTest.java
https://tools.hmcts.net/jira/browse/ST-714
```
[ ] Yes
[x] No
```
=> ST-714 Message Fixed

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateHearingSummary.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/service/HearingService.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/HearingVenues.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCreateHearingSummaryTest.java
=> ST-701- screen for 'Hearing location and duration'

src/main/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtil.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/ContactPreferenceType.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/ApplicantDetails.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/RepresentativeDetails.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/SubjectDetails.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCancelHearingTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrderTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtilTest.java, src/test/java/uk/gov/hmcts/sptribs/common/event/page/ApplicantDetailsTest.java, src/test/java/uk/gov/hmcts/sptribs/common/event/page/RepresentativeDetailsTest.java, src/test/java/uk/gov/hmcts/sptribs/common/event/page/SubjectDetailsTest.java
https://tools.hmcts.net/jira/browse/ST-964
```
[ ] Yes
[x] No
```
=> ST-964 Contact Preference Type Check

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCancelHearing.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCancelHearingTest.java
https://tools.hmcts.net/jira/browse/ST-714
```
[ ] Yes
[x] No
```
=> ST-714 fixed status change

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecision.java
https://tools.hmcts.net/jira/browse/ST-767
Remove text that is no longer required.
```
[ ] Yes
[x] No
```
=> ST-767 Remove redundant text

build.gradle, src/main/java/uk/gov/hmcts/sptribs/common/ccd/HighLevelDataSetupApp.java
https://tools.hmcts.net/jira/browse/ST-939
```
[ ] Yes
[ ] No
```
=> ST-939-new roles added

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueCase.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/java/uk/gov/hmcts/sptribs/common/CommonConstants.java, src/main/java/uk/gov/hmcts/sptribs/notification/NotificationHelper.java
=> ST-831: respondent mail issue fixed

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/java/uk/gov/hmcts/sptribs/common/CommonConstants.java, src/main/java/uk/gov/hmcts/sptribs/notification/NotificationHelper.java
=> ST-831: rolledback cica ref changes for change in story

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerContactParties.java
* Created confirmation page for contact parties
* Change teste for contact parties
* Changes the saved message according to the parties elected.
* changes the state of contact parties
* changes the state of contact parties
* changes the message after submit case
* write some tests
* write some tests
* write some tests
* write some tests
* Changes made to message
```
[ ] Yes
[ ] No
```
=> Feat/st 680 (#335)

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueFinalDecisionSelectRecipients.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseIssueFinalDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtil.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecisionTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueFinalDecisionSelectRecipientsTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtilTest.java
https://tools.hmcts.net/jira/browse/ST-763
```
[ ] Yes
[x] No
```
=> ST-763 Select Recipients labels

build.gradle, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/HearingVenues.java
https://tools.hmcts.net/jira/browse/ST-701
```
[ ] Yes
[x] No
```
=> ST-701 Hearing venue readonly

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateHearingSummary.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerPostponeHearing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CancelHearingDateSelect.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/PostponeHearingSelectHearing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/HearingSummary.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerPostponeHearingTest.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestEventConstants.java
https://tools.hmcts.net/jira/browse/ST-718
```
[ ] Yes
[x] No
```
=> ST-718 Postpone hearing journey start

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerPostponeHearing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/PostponeHearingSelectReason.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/PostponeReason.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java
https://tools.hmcts.net/jira/browse/ST-720
```
[ ] Yes
[x] No
```
=> ST-720 Reason for postponement

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerPostponeHearing.java
https://tools.hmcts.net/jira/browse/ST-721
```
[ ] Yes
[x] No
```
=> ST-721 check answers

src/main/java/uk/gov/hmcts/sptribs/caseworker/helper/RecordListHelper.java
https://tools.hmcts.net/jira/browse/ST-685
Spit text into two paragraphs as shown on the ticket.
```
[ ] Yes
[x] No
```
=> ST-685 Split text into two paragraphs

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/FullPanelHearing.java
=> ST-702 fixed the typo

src/main/java/uk/gov/hmcts/sptribs/common/event/page/HearingVenues.java
https://tools.hmcts.net/jira/browse/ST-701
```
[ ] Yes
[x] No
```
=> ST-701 Hearing Venue display

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerPostponeHearing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/PostponeHaringNotifyParties.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerPostponeHearingTest.java
https://tools.hmcts.net/jira/browse/ST-841
```
[ ] Yes
[x] No
```
=> ST-841 Postpone Hearing notify parties

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCancelHearing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtil.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtilTest.java
https://tools.hmcts.net/jira/browse/ST-691
Refactor MessageUtil to remove code duplication.  Add record listing confirmation message.
```
[ ] Yes
[x] No
```
=> ST-691 Edit record listing confirmation message

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/PostponeHearingSelectReason.java
https://tools.hmcts.net/jira/browse/ST-720
```
[ ] Yes
[x] No
```
=> ST-720 Reasons for postponement

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/PostponeHaringNotifyParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/PostponeHearingSelectHearing.java
https://tools.hmcts.net/jira/browse/ST-841
```
[ ] Yes
[x] No
```
=> ST-841 Notify parties

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerPostponeHearing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtil.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerPostponeHearingTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtilTest.java
https://tools.hmcts.net/jira/browse/ST-722
```
[ ] Yes
[x] No
```
=> ST-722 Postpone conformation page

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/RecordListing.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/HearingVenues.java
=> Fix required - Record and Edit listing (Listing Details)

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/HearingVenues.java
=> ST-1016 Error fixes

src/main/java/uk/gov/hmcts/sptribs/common/notification/ListingUpdatedNotification.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/ListingUpdatedNotificationTest.java
=> ST-838: fixed hearing venue issue

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditRecordListing.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditRecordListingTest.java
=> ST-1016 Edit Page fix

src/main/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtil.java
https://tools.hmcts.net/jira/browse/ST-691
```
[ ] Yes
[x] No
```
=> ST-691 Correct notification message

src/main/java/uk/gov/hmcts/sptribs/notification/NotificationHelper.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/NotificationHelperTest.java
=> St 833 hearing info venue fix

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/PostponeHaringNotifyParties.java
https://tools.hmcts.net/jira/browse/ST-841
```
[ ] Yes
[x] No
```
=> ST-841 Message

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloseTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseWithdrawalDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CloseCase.java
https://tools.hmcts.net/jira/browse/ST-773
Add Close case withdrawal details screen
```
[ ] Yes
[x] No
```
=> ST-773 Add Close case withdrawal details screen

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloseTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseRejectionDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CloseCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CloseCaseRejectionReason.java
https://tools.hmcts.net/jira/browse/ST-786
Add Close Case rejection details page
```
[ ] Yes
[x] No
```
=> ST-786 Add Close Case rejection details page

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloseTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseConcessionDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseRejectionDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CloseCase.java
https://tools.hmcts.net/jira/browse/ST-797
Add Close Case rejection details page
```
[ ] Yes
[x] No
```
=> ST-797 Add Close Case concession details page

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloseTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseConsentOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseRejectionDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseWithdrawalDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CloseCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CloseReason.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/State.java
https://tools.hmcts.net/jira/browse/ST-799
Add Close Case consent order page
```
[ ] Yes
[x] No
```
=> ST-799 Add Close Case consent order page

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml, .github/renovate.json, .github/stale.yml, .github/workflows/ci.yml, Jenkinsfile_CNP, bin/clone-vaults.sh
https://tools.hmcts.net/jira/browse/ST-936
```
[ ] Yes
[x ] No
```
=> ST-936-github actions for e2e and integration tests

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/HearingVenues.java
=> ST-1016 Dynamiclist Error

src/main/java/uk/gov/hmcts/sptribs/common/ccd/HighLevelDataSetupApp.java
Attempt to fix the failure to import ccd-CriminalInjuriesCompensation-aat.xlsx.
https://tools.hmcts.net/jira/browse/SPTRIBS-1050
=> Add respondent ccd role

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueCaseNotifyParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueDecisionSelectRecipients.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueFinalDecisionSelectRecipients.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/PostponeHaringNotifyParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/RecordNotifyParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReinstateNotifyParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/SendOrderNotifyParties.java
Recipient Lables changed
https://tools.hmcts.net/jira/browse/ST-1031
=> ST-1031 Recipient Labels

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateHearingSummary.java
State changed to Awaiting Outcome
https://tools.hmcts.net/jira/browse/ST-1058
=> ST-1058 State change after event

src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerAddNoteIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerCreateGeneralLetterIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerIssueCaseIT.java, src/main/java/uk/gov/hmcts/sptribs/common/config/WebMvcConfig.java, src/main/java/uk/gov/hmcts/sptribs/common/config/advice/GlobalExceptionHandler.java, src/main/java/uk/gov/hmcts/sptribs/common/config/interceptors/RequestInterceptor.java, src/main/java/uk/gov/hmcts/sptribs/common/config/interceptors/UnAuthorisedServiceException.java, src/test/java/uk/gov/hmcts/sptribs/common/config/advice/GlobalExceptionHandlerTest.java, src/test/java/uk/gov/hmcts/sptribs/common/config/interceptors/RequestInterceptorTest.java
https://tools.hmcts.net/jira/browse/ST-1028
=> ST-1028 Revert changes that break integration tests.

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditRecordListing.java
=> ST-1016 Edit Listing Error

charts/sptribs-case-api/values.yaml, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml
The AAT judicial ref data API url is incorrect.
https://tools.hmcts.net/jira/browse/SPTRIBS-794
=> ST-794 Fix judicial ref data API url

charts/sptribs-case-api/Chart.yaml
Need to bump Chart.yaml version to publish new chart version
https://tools.hmcts.net/jira/browse/ST-794
=> ST-794 Bump Chart.yaml version

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateHearingSummary.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java
additional hearing date fix
https://tools.hmcts.net/jira/browse/ST-701
=> ST-701 Additional Hearing Dates fix

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueCaseNotifyParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueDecisionSelectRecipients.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/PostponeHaringNotifyParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/RecordNotifyParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReinstateNotifyParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/SelectRecipientsHelper.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/SendOrderNotifyParties.java
Label change
https://tools.hmcts.net/jira/browse/ST-1031
=> ST-1031 Labels changed

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloseTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/service/HearingService.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtil.java, src/main/java/uk/gov/hmcts/sptribs/judicialrefdata/JudicialService.java, src/main/java/uk/gov/hmcts/sptribs/recordlisting/LocationService.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtilTest.java
Adds the notification parties to the
confirmation message.  Removes the creation of
an empty list value from judicial service, since
this makes it appear as if the user selection is
optional.  Applies the same fix to the HearingService and LocationService as well.
https://tools.hmcts.net/jira/browse/ST-786
=> ST-794 Close case rework

src/main/java/uk/gov/hmcts/sptribs/caseworker/service/OrderService.java, src/main/java/uk/gov/hmcts/sptribs/recordlisting/LocationService.java
Empty Line fix
https://tools.hmcts.net/jira/browse/ST-963
=> ST-963 Dynamiclist empty line

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerContactParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateHearingSummary.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerIssueDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerManageOrderDueDate.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerPostponeHearing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerAddNote.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCancelHearing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseFlag.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloseTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerManageCaseFlag.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRemoveStay.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStayTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/TestStateChange.java
=> remove .showEventNote() method from event declaration .

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/HearingOutcome.java
Fixed typo
https://tools.hmcts.net/jira/browse/ST-704
=> ST-704 - fixed typo

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/RecordListing.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/HearingVenues.java, src/main/java/uk/gov/hmcts/sptribs/notification/NotificationHelper.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/ListingCreatedNotificationTest.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/ListingUpdatedNotificationTest.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/NotificationHelperTest.java
Merge hearing venue name and address
https://tools.hmcts.net/jira/browse/ST-833
=> ST-833 Merge hearing venue name and address

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerIssueDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueDecisionMainContent.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/DraftOrderMainContentPage.java, src/main/java/uk/gov/hmcts/sptribs/document/content/DecisionTemplateContent.java, src/main/java/uk/gov/hmcts/sptribs/document/content/DocmosisTemplateConstants.java, src/test/java/uk/gov/hmcts/sptribs/document/content/DecisionTemplateContentTest.java
Issue Decision Main Content Page
https://tools.hmcts.net/jira/browse/ST-934
=> ST-934 Issue Decision Main Content Page

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateHearingSummary.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtil.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCreateHearingSummaryTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/MessageUtilTest.java
Hearing summary confirmation message
https://tools.hmcts.net/jira/browse/ST-707
=> ST-707 Hearing summary confirmation message

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCancelHearing.java
Message Fixed
https://tools.hmcts.net/jira/browse/ST-980
=> ST-980 Message Fixed

src/main/java/uk/gov/hmcts/sptribs/caseworker/util/PageShowConditionsUtil.java
Page Show Conditions
https://tools.hmcts.net/jira/browse/ST-934
=> ST-934 Page Show Conditions

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/FinalDecisionTemplate.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecisionTest.java
Missing Templates
https://tools.hmcts.net/jira/browse/ST-762
=> ST-762 Missing Templates

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/SendOrderAddDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java
Preview of draft orders removed
https://tools.hmcts.net/jira/browse/ST-997
=> ST-997 Preview of draft orders removed

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/DraftOrderMainContentCIC.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/DraftOrderMainContentPage.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/PreviewDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/document/content/PreviewDraftOrderTemplateContent.java
Add main content to draft order document
https://tools.hmcts.net/jira/browse/ST-974
=> ST-974 Add main content to draft order doc

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/HearingSummary.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/HearingRecordingUploadPage.java
Add label for recording description
https://tools.hmcts.net/jira/browse/ST-706
=> ST-706 Add label for recording description

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseLink.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseLinksElement.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/LinkReason.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/SubjectDetails.java, src/test/java/uk/gov/hmcts/sptribs/common/event/page/SubjectDetailsTest.java
Post address is mandatory for subject
https://tools.hmcts.net/jira/browse/ST-1025
=> ST-1025 Post address is mandatory for subject

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/OrderTemplate.java
changed the letter inconsistency in dropdown list for Order Template
=> ST-954 , Update document template dropdown list .

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueFinalDecisionMainContent.java
Page label fix
https://tools.hmcts.net/jira/browse/ST-896
=> ST-896 Page label

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueDecisionMainContent.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueFinalDecisionMainContent.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java
main content label
https://tools.hmcts.net/jira/browse/ST-896
=> ST-896 Main content label fix

src/main/java/uk/gov/hmcts/sptribs/common/event/page/SubjectDetails.java, src/test/java/uk/gov/hmcts/sptribs/common/event/page/SubjectDetailsTest.java
rule change
https://tools.hmcts.net/jira/browse/ST-1025
=> ST-1025 rule change

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/DraftOrderCIC.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrderTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrderTest.java
Save edited content to order
https://tools.hmcts.net/jira/browse/ST-974
=> ST-974 Save edited content to order

src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Base.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Case.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/CloseCase.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Login.java, src/e2eTests/java/uk/gov/hmcts/sptribs/testutils/PageHelpers.java
Changes in Subject details screen of Create case journey is causing the failure of AAT e2e create case test. This PR includes a fix for the test and some improvements for the browser type in the base class and other tests.
https://tools.hmcts.net/jira/browse/ST-1081
=> [ST-1081]: Fix the failing AAT e2e create case test for the changes in Subject details screen

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerManageOrderDueDate.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ManageSelectOrders.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/DraftOrderContentCIC.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrderTest.java
This order also contains some code from feat/ST-117 but mainly some fixes for  964
=> Feat/st 996 Drfat order is no longer draft when sent

config/owasp/suppressions.xml
Suppress CVE causing false positive
=> Suppress CVE causing false positive

src/main/java/uk/gov/hmcts/sptribs/common/event/page/ApplicantDetails.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/RepresentativeDetails.java, src/test/java/uk/gov/hmcts/sptribs/common/event/page/ApplicantDetailsTest.java, src/test/java/uk/gov/hmcts/sptribs/common/event/page/RepresentativeDetailsTest.java
Town city validation for applicant and representative
https://tools.hmcts.net/jira/browse/ST-1025
=> ST-1025 Town city validation for applicant and representative

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerManageOrderDueDate.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/service/OrderService.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/service/OrderServiceTest.java
Manage order page order list
https://tools.hmcts.net/jira/browse/ST-1108
=> ST-1108 Manage order page order list

Jenkinsfile_CNP
=> internal update

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReinstateUploadDocuments.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCaseTest.java
Reinstate document check description
https://tools.hmcts.net/jira/browse/ST-780
=> ST-780 Reinstate document check description

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerManageOrderDueDate.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ManageSelectOrders.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/service/OrderService.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/service/OrderServiceTest.java
Select sent orders
https://tools.hmcts.net/jira/browse/ST-996
=> ST-996 Select sent orders

src/main/java/uk/gov/hmcts/sptribs/common/event/page/SubjectDetails.java
Subject Details page
https://tools.hmcts.net/jira/browse/ST-1104
=> ST-1104 Subject Details page

Jenkinsfile_CNP, config/owasp/suppressions.xml, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerContactParties.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerContactPartiesTest.java
First feature flag
https://tools.hmcts.net/jira/browse/ST-1109
=> ST-1109 First feature flag

Jenkinsfile_nightly
product update
https://tools.hmcts.net/jira/browse/ST-1089
=> product update

Jenkinsfile_CNP, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerMaintainLinkCase.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCaseTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerMaintainLinkCaseTest.java
Feature flag for link case
https://tools.hmcts.net/jira/browse/ST-1111
=> ST-1111 Feature flag for link case

Jenkinsfile_CNP, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseFlag.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerManageCaseFlag.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseFlagTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerManageCaseFlagTest.java
Feature flag for case flag
https://tools.hmcts.net/jira/browse/ST-1112
=> ST-1112 Feature flag for case flag

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerIssueDecision.java
Label fix on issue decision
https://tools.hmcts.net/jira/browse/ST-1121
=> ST-1121 Label fix on issue decision

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerChangeSecurityClassification.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/SecurityClass.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/SecurityUtil.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/common/event/CreateTestCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerChangeSecurityClassificationTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/SecurityUtilTest.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestDataHelper.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestEventConstants.java
Security Classficiation Change Page
https://tools.hmcts.net/jira/browse/ST-1086
=> ST-1086 Security Classficiation Change Page

src/main/java/uk/gov/hmcts/sptribs/caseworker/service/HearingService.java
Label on dropdown
https://tools.hmcts.net/jira/browse/ST-1002
=> ST-1002 Label on dropdown

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java
record listing removed from awaiting hearing state
https://tools.hmcts.net/jira/browse/ST-998
=> record listing removed from awaiting hearing state

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/EditHearingSummarySelect.java
Label change
https://tools.hmcts.net/jira/browse/ST-1002
=> ST-1002 Label change

src/cftlibTest/java/uk/gov/hmcts/sptribs/cftlib/CaseworkerCloseCaseTest.java, src/cftlibTest/java/uk/gov/hmcts/sptribs/cftlib/CaseworkerRecordListingTest.java
https://tools.hmcts.net/jira/browse/ST-1072
=> ST-1072 Disabled until pipeline issue solved

src/main/java/uk/gov/hmcts/sptribs/citizen/event/CicCreateCaseEvent.java, src/main/java/uk/gov/hmcts/sptribs/common/event/CreateTestCase.java, src/test/java/uk/gov/hmcts/sptribs/citizen/event/CicCreateCaseEventTest.java
Allow SOLICITOR and COURT_ADMIN_CIC to
create cases in all envs.  Allow SUPER_USER
to create case in all non-prod envs.
Only allow CITIZEN_CIC role to create DSS case.
https://tools.hmcts.net/jira/browse/ST-1027
=> ST-1027 Change event permissions

Jenkinsfile_CNP
Added ITHC Case API to Jenkins_CNP file
=> Added ITHC case API configuration to Jenkins_CNP file

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToLegalOfficer.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToLegalOfficerTest.java
https://tools.hmcts.net/jira/browse/ST-1143
=> refer to officer event added

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditCicaCaseDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/EditCicaCaseDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/EditCicaCaseDetailsPage.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditCicaCaseDetailsTest.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestEventConstants.java
Created Edit cica case details in the drop down to start event
=> feat/ST-995 Created Edit cica case details in the drop down to start event

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReferToJudgeReason.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/ReferToJudge.java
Change radio buttons to dropdown and fix PMD
https://tools.hmcts.net/jira/browse/ST-1139
=> ST-1139 Change radio buttons to dropdown

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToJudge.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReferToJudgeAdditionalInfo.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReferToJudgeReason.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/ReferToJudge.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToJudgeTest.java
Add additional info page
https://tools.hmcts.net/jira/browse/ST-1140
=> ST-1140 Add additional info page

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditCicaCaseDetails.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditCicaCaseDetailsTest.java
Create a page to display  Case details updated message
https://tools.hmcts.net/jira/browse/ST-994
=> Feat/ST-994 Create a page to display  Case details updated message

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseRejectionDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseStrikeOutDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CloseCaseRejectionReason.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CloseCaseStrikeOutReason.java
Label and reason changes
https://tools.hmcts.net/jira/browse/ST-1134
=> ST-1134 Label and reason changes

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagement.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/UploadCaseDocuments.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/DocumentManagement.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/document/model/CaseworkerCICDocument.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementTest.java
Document Management Upload event
https://tools.hmcts.net/jira/browse/ST-484
https://tools.hmcts.net/jira/browse/ST-350
https://tools.hmcts.net/jira/browse/ST-422
https://tools.hmcts.net/jira/browse/ST-1127
=> ST-484: Document Management Upload event

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToJudge.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToLegalOfficer.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReferToLegalOfficer.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReferToLegalOfficerAdditionalInfo.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/ReferToLegalOfficer.java
https://tools.hmcts.net/jira/browse/ST-1145
=> refer additional page added

src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java
Hearings Page
https://tools.hmcts.net/jira/browse/ST-1126
=> ST-1126 Hearings Page

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToLegalOfficer.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToLegalOfficerTest.java
Conformation Page
https://tools.hmcts.net/jira/browse/ST-1147
=> ST-1147 Conformation Page

build.gradle
JVM parameter add for JAVA 17
https://tools.hmcts.net/jira/browse/ST-1158
=> ST-1158 JVM parameter add for JAVA 17

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueDecisionPreviewTemplate.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueFinalDecisionPreviewTemplate.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseIssueDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseIssueFinalDecision.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/CaseFinalDecisionIssuedNotification.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/DecisionIssuedNotification.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTabTest.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/CaseFinalDecisionIssuedNotificationTest.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/DecisionIssuedNotificationTest.java
Orders and decisions tab
https://tools.hmcts.net/jira/browse/ST-1156
=> ST-1156 Orders and decisions tab

charts/sptribs-case-api/Chart.yaml, charts/sptribs-case-api/values.yaml
Reverts hmcts/sptribs-case-api#688
=> Revert "ST-1150-Update values.yaml"

src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java
=> ST-1117. tabs added to district judge role

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/RecordNotifyParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/Listing.java
=> fix bugs ST-1155 , items 13 , 14

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerManageOrderDueDate.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java
=> ST-1157 , remove caseworker events when case status in awaiting outcome

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementRemove.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReinstateUploadDocuments.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ShowCaseDocuments.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CloseCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/HearingSummary.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/service/DocumentListService.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementRemoveTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCaseTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/service/DocumentListServiceTest.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestEventConstants.java
Document Remove Page
https://tools.hmcts.net/jira/browse/ST-1128
=> ST-1128 Document Remove Page

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementRemove.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/service/DocumentListService.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/OrderDocumentListUtil.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/service/DocumentListServiceTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/OrderDocumentListUtilTest.java
Check answers adn PMD fixes
https://tools.hmcts.net/jira/browse/ST-1130
=> ST-1130 Check answers and PMD fixes

config/owasp/suppressions.xml
CVE 2023-20861 addition
https://tools.hmcts.net/jira/browse/ST-1202
=> ST-1202 CVE 2023-20861

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementRemove.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/service/DocumentListService.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DecisionDocumentListUtil.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/OrderDocumentListUtil.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/service/DocumentListServiceTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/DecisionDocumentListUtilTest.java
Conformation page and PMD fixes
https://tools.hmcts.net/jira/browse/ST-1132
=> ST-1132 Conformation page and PMD fixes

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementRemove.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DecisionDocumentListUtil.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/OrderDocumentListUtil.java
PMD fixes
https://tools.hmcts.net/jira/browse/ST-1132
=> ST-1132 PMD fixes

src/integrationTest/java/uk/gov/hmcts/sptribs/testutil/DocManagementStoreWireMock.java, src/integrationTest/java/uk/gov/hmcts/sptribs/testutil/IdamWireMock.java, src/main/java/uk/gov/hmcts/sptribs/common/ccd/HighLevelDataSetupApp.java
=> ST-1077_Redundant_Code_PR1 Removed some redundant code.

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagement.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/UploadCaseDocuments.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/DocumentManagement.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java
Updated description and Case Document Tab
https://tools.hmcts.net/jira/browse/ST-1127
https://tools.hmcts.net/jira/browse/ST-422
=> Feat/st 1127: Updated description and Case Document Tab

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/SecurityClass.java
Fix roles for each class
https://tools.hmcts.net/jira/browse/ST-1086
=> ST-1086 Fix roles for each class

src/main/resources/application.yaml
Fix env var name
https://tools.hmcts.net/jira/browse/ST-1113
=> ST-1113 Fix env var name

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementAmend.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementAmendTest.java
https://tools.hmcts.net/jira/browse/ST-1131
=> ST-1131 amend document

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementRemove.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ShowCaseDocuments.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ShowRemovedCaseDocuments.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtil.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementRemoveTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtilTest.java
Document Management Remove-Removed File List
https://tools.hmcts.net/jira/browse/ST-1130
=> ST-1130 Document Management Remove-Removed File List

src/main/resources/application.yaml
=> enable debug logging at application.yaml

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ShowCaseDocuments.java, src/main/resources/application.yaml
Remove List changes
https://tools.hmcts.net/jira/browse/ST-1130
=> ST-1130 Remove List changes

Jenkinsfile_CNP
Reverts hmcts/sptribs-case-api#801
=> Revert "Revert "ST-1151-Update build.gradle for e2e test""

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/access/CitizenAccess.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/model/access/CitizenAccessTest.java
Add pcqId field
https://tools.hmcts.net/jira/browse/ST-931
=> ST-931 Add pcqId field

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ShowCaseDocuments.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DecisionDocumentListUtil.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtil.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentManagementUtil.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/OrderDocumentListUtil.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementRemoveTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/DecisionDocumentListUtilTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtilTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentManagementUtilTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/OrderDocumentListUtilTest.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestDataHelper.java
PMD error fix
https://tools.hmcts.net/jira/browse/ST-1130
=> ST-1130 PMD error fix

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueCaseAdditionalDocument.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueCaseSelectDocument.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/ApplicationEvidence.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseIssue.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/TribunalDocuments.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtil.java, src/main/java/uk/gov/hmcts/sptribs/common/CommonConstants.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/CaseIssuedNotification.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueCaseTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtilTest.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/CaseIssuedNotificationTest.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestDataHelper.java
Select additional documentation
=> ST-645 Select additional documentation

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/ST-1089
=> ST-1089-disable_security_scan on Jenkinsfile_nightly

Jenkinsfile_nightly
Reverts hmcts/sptribs-case-api#822
=> "ST-1089-disable_security_scan on Jenkinsfile_nightly"

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloneBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCreateBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStitchBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/State.java, src/main/java/uk/gov/hmcts/sptribs/document/bundling/BundleSubFolder.java, src/main/java/uk/gov/hmcts/sptribs/document/bundling/BundleSubFolder2.java, src/main/resources/bundleconfiguration/bundle.yaml, src/main/resources/bundleconfiguration/bundle_all_case.yaml, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloneBundleTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCreateBundleTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditBundleTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStitchBundleTest.java, src/test/java/uk/gov/hmcts/sptribs/document/bundling/BundleTest.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestEventConstants.java, src/test/resources/case.json
Adding bundling events and fields to CCD config
https://tools.hmcts.net/jira/browse/ST-856
=> ST-856 Adding bundling events and fields to CCD config

Jenkinsfile_CNP
Enables these features on aat and prod
ST-1259 Enable case file view and document management
https://tools.hmcts.net/jira/browse/ST-1259
=> ST-1259 Enable case file view and document management

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ShowCaseDocuments.java
Error message when no documents removed
https://tools.hmcts.net/jira/browse/ST-1129
=> ST-1129 Error message when no documents removed

src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/IssueToRespondent.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueCaseAdditionalDocument.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/TribunalDocuments.java
=> ST-645 Labels fixed

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueCaseSelectDocument.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtil.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentManagementUtil.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentManagementUtilTest.java
=> ST-645 PMD fix

Jenkinsfile_CNP
Reverts hmcts/sptribs-case-api#838
=> Revert "Feat/st 1030: Update build.gradle for e2e test"

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/RespondentPartiesToContact.java
https://tools.hmcts.net/jira/browse/ST-1200
=> St 1200 - 

Jenkinsfile_CNP
Reverts hmcts/sptribs-case-api#839
=> Revert "Revert "Feat/st 1030: Update build.gradle for e2e test""

Jenkinsfile_nightly
Load vault secrets
https://tools.hmcts.net/jira/browse/ST-1170
=> ST-1170 Load vault secrets

Jenkinsfile_nightly
Add missing secret() method
https://tools.hmcts.net/jira/browse/ST-1170
=> ST-1170 Add missing secret() method

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementAmend.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementAmendTest.java
Document Amend Confformation Screen
https://tools.hmcts.net/jira/browse/ST-1137
=> ST-1137 Document Amend Confformation Screen

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueCaseSelectDocument.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/CaseIssuedNotification.java
=> ST-645 Notification fix

src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtil.java, src/main/java/uk/gov/hmcts/sptribs/document/model/CaseworkerCICDocument.java, src/test/java/uk/gov/hmcts/sptribs/document/model/CaseworkerCICDocumentTest.java
=> ST-645 Filtered unattachable files

src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventUtil.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/OrderTemplate.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/EventUtilTest.java, src/test/java/uk/gov/hmcts/sptribs/document/content/PreviewDraftOrderTemplateContentTest.java
Rollback from master
https://tools.hmcts.net/jira/browse/ST-1261
=> ST-1261 Rollback from master

Jenkinsfile_CNP, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloneBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCreateBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStitchBundle.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloneBundleTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCreateBundleTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditBundleTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStitchBundleTest.java
Add feature flag for bundling
https://tools.hmcts.net/jira/browse/ST-1110
=> ST-1110 Add feature flag for bundling

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/NewOrderIssuedNotification.java
Send order Issues
https://tools.hmcts.net/jira/browse/ST-1334
=> ST-1334 Send order Issues

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloseTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseConsentOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseRejectionDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseRule27.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseStrikeOutDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseWithdrawalDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CloseCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CloseReason.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/State.java
=> apply fix ST-1260 and ST-1262

src/main/java/uk/gov/hmcts/sptribs/document/DocumentUtil.java, src/main/java/uk/gov/hmcts/sptribs/document/model/CaseworkerCICDocument.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCloseTheCaseTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueCaseTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCaseTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/page/HearingRecordingUploadPageTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReinstateUploadDocumentsTest.java, src/test/java/uk/gov/hmcts/sptribs/document/DocumentUtilTest.java, src/test/java/uk/gov/hmcts/sptribs/document/model/CaseworkerCICDocumentTest.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestDataHelper.java
Fix document validation bugs
https://tools.hmcts.net/jira/browse/ST-1335
=> ST-1335 Fix document validation bugs

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagAdditionalInfo.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java
[Additional comments page](https://github.com/hmcts/sptribs-case-api/pull/865)
=> Feat/st 443 Additional comments page 

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerManageCaseFlag.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ManageFlagShowList.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/service/FlagService.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerManageCaseFlagTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/service/FlagServiceTest.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestDataHelper.java
Manage flag- flag list
https://tools.hmcts.net/jira/browse/ST-447
=> ST-447 Manage flag- flag list

src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventUtil.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/OrderTemplate.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/EventUtilTest.java, src/test/java/uk/gov/hmcts/sptribs/document/content/PreviewDraftOrderTemplateContentTest.java
CIC3 Rule 27 (Order).
https://tools.hmcts.net/jira/browse/ST-1261
=> Feat/st 1261  CIC3 Rule 27 (Order)

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagAdditionalInfo.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagLevel.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagTypePage.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/CheckRequiredUtil.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/CheckRequiredUtilTest.java
Flag location
https://tools.hmcts.net/jira/browse/ST-441
=> ST-441 Flag Location

Jenkinsfile_CNP, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/ST-1336
=> ST-1336 Flag disable for R1

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerManageCaseFlag.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ManageFlagShowList.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ManageFlagUpdate.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerManageCaseFlagTest.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestDataHelper.java
Manage flags update and save 
https://tools.hmcts.net/jira/browse/ST-456
=> Feat/ST- 456 Manage flags update and save 

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle
=> ST-1172 Run e2eTests on preview with msedge

src/main/java/uk/gov/hmcts/sptribs/services/CaseManagementService.java
Fixing a typo and a code smell re String literal.
https://tools.hmcts.net/jira/browse/ST-1349
=> ST-1349 Fixing typo and code smell about String literal.

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCase.java
History tab
https://tools.hmcts.net/jira/browse/ST-1345
=> ST-1345 History Tab

src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtil.java, src/main/java/uk/gov/hmcts/sptribs/document/model/CICDocument.java, src/main/java/uk/gov/hmcts/sptribs/document/model/CaseworkerCICDocument.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecisionTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueDecisionUploadNoticeTest.java, src/test/java/uk/gov/hmcts/sptribs/document/DocumentUtilTest.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestDataHelper.java
Document type validation changed
https://tools.hmcts.net/jira/browse/ST-1120
=> ST-1120 Document type validation changed

Jenkinsfile_CNP
Removing vaultOverrides
https://tools.hmcts.net/jira/browse/ST-1357
=> ST-1357 Removing vaultOverrides for preview and prod.

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerAddNote.java
Case list
https://tools.hmcts.net/jira/browse/ST-1358
=> ST-1348 Case list

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/search/CaseFieldsConstants.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/model/CaseDataTest.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/model/CicCaseTest.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/workbasket/WorkBasketInputFieldsTest.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/workbasket/WorkBasketResultFieldsTest.java
Search results
https://tools.hmcts.net/jira/browse/ST-1343
=> ST-1343 Search results

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/service/OrderService.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateDraftOrderTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrderTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/service/OrderServiceTest.java
Order file duplication
https://tools.hmcts.net/jira/browse/ST-1361
=> ST-1361 Order file duplication

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ContactPartiesSelectDocument.java
Excel added to note
https://tools.hmcts.net/jira/browse/ST-677
=> ST-677 Excel added to note

Jenkinsfile_CNP, build.gradle
=> Added e2e test to Preview environment ST1360

src/main/java/uk/gov/hmcts/sptribs/common/CommonConstants.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/CaseIssuedNotification.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/ContactPartiesNotification.java, src/main/java/uk/gov/hmcts/sptribs/notification/NotificationHelper.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/ContactPartiesNotificationTest.java
Updated the Notification logic for Contact parties
https://tools.hmcts.net/jira/browse/ST-847
=> ST-847: Updated the Notification logic for Contact parties

build.gradle, src/cftlibTest/java/uk/gov/hmcts/sptribs/cftlib/CaseworkerCloseCaseTest.java, src/cftlibTest/java/uk/gov/hmcts/sptribs/cftlib/CreateCaseTest.java, src/cftlibTest/java/uk/gov/hmcts/sptribs/cftlib/EditCaseTest.java, src/cftlibTest/java/uk/gov/hmcts/sptribs/cftlib/StayCaseTest.java
fix pipeline failure because of missing docker version
=> fix pipeline failure because of missing docker version

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java
https://tools.hmcts.net/jira/browse/ST-1349
=> ST-1369 Fixing SonarLint code smell

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/RespondentContactParties.java
Added include documents page
https://tools.hmcts.net/jira/browse/ST-1377
=> ST-1377: Added include documents page

build.gradle, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Base.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Case.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/DssCase.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/DssCaseTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Login.java, src/e2eTests/java/uk/gov/hmcts/sptribs/testutils/PageHelpers.java
This PR adds required methods to create case via DSS journey and adds a DSS Front end E2E test to create a case via DSS and verify that case is displayed in case api backend. This test is disabled at the moment. The test assertions will be extended and enabled once the preview environment is stable and the case details are displayed in backend.
https://tools.hmcts.net/jira/browse/ST-1081
=> Add DSS front end E2E tests

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java
Due date calculation error
https://tools.hmcts.net/jira/browse/ST-1343
=> ST-1343 Due date calculation error

src/main/resources/application.yaml
=> spring config from dss backend added for doc upload

charts/sptribs-case-api/values.preview.template.yaml
Pointing to Service_Name url of ccd-data-atore-api
=> ST-847: Pointing to Service_Name url

charts/sptribs-case-api/values.preview.template.yaml
Pointing to Change_Id specific urls in Preview yaml. This is to see if the issue with CDAM API is getting fixed,
https://tools.hmcts.net/jira/browse/ST-847
=> Feat/st 847 1: Pointing to Change_Id specific urls in Preview yaml

charts/sptribs-case-api/values.preview.template.yaml, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerContactParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java
Added exception block for Contact Parties Notification
https://tools.hmcts.net/jira/browse/ST-847
=> Feat/st 847 1: Added exception block for Contact Parties Notification

charts/sptribs-case-api/Chart.yaml, charts/sptribs-case-api/values.yaml
=> S2s update

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/UserRole.java
citizen_sptribs_cic_dss role changed into citizen
https://tools.hmcts.net/jira/browse/ST-1408
=> ST-1408 citizen_sptribs_cic_dss role changed into citizen

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/UserRole.java
=> Update UserRole.java CRU update

Jenkinsfile_CNP, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Base.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Case.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/ContactPartiesTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/DocumentManagement.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/DocumentManagementTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Hearing.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/IssueADecisionTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/IssueFinalDecisionTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/IssueToRespondentTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Login.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/ReferCaseToJudgeTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/enums/Actions.java, src/e2eTests/java/uk/gov/hmcts/sptribs/testutils/PageHelpers.java
This PR is to enable tests which are disabled previously. Some tests are disabled as there are bugs raised to fix them. These are disabled for the moment and will be enabled when the relevant issues are fixed.
https://tools.hmcts.net/jira/browse/ST-1408
=> [ST-1081]: update and enable e2e tests

src/main/java/uk/gov/hmcts/sptribs/citizen/event/CicUpdateCaseEvent.java
DSS integration
https://tools.hmcts.net/jira/browse/ST-1385
=> ST-1385 DSS integration

charts/sptribs-case-api/values.preview.template.yaml
=> St 1358 es changes

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/ST-955
=> St 955 Large file upload

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementAmend.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/java/uk/gov/hmcts/sptribs/citizen/event/CicUpdateCaseEvent.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementAmendTest.java, src/test/java/uk/gov/hmcts/sptribs/citizen/event/CicUpdateCaseEventTest.java
DSS integration bugs
https://tools.hmcts.net/jira/browse/ST-1420
=> ST-1420 DSS integration bugs

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/EditDraftOrder.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateDraftOrderTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrderTest.java
DSS integration
https://tools.hmcts.net/jira/browse/ST-1420
=> ST-1420 DSS integration

build.gradle, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/DssCaseTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/enums/CaseState.java
This PR is to enable the DSS E2E Tests to run as part of the Preview pipeline
https://tools.hmcts.net/jira/browse/ST-1081
=> [ST-1081]: enable DSS E2E Tests

src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Case.java
=> Change Continue to Submit on Case Built

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseSubcategory.java
Added few more values to sub-category drop-down list.
https://tools.hmcts.net/jira/browse/SNI-4025
=> SNI-4025: Added few more values to sub-category drop-down list.

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerAddNote.java, src/main/java/uk/gov/hmcts/sptribs/common/event/CreateTestCase.java
History tab missing events
https://tools.hmcts.net/jira/browse/ST-1345
=> ST-1345 History tab missing events

build.gradle, config/owasp/suppressions.xml, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Case.java
=> Change Continue to Submit on Case Built and change DSS environment

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagement.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/RespondentDocumentManagement.java, src/main/java/uk/gov/hmcts/sptribs/document/DocumentUtil.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/RespondentDocumentManagementTest.java, src/test/java/uk/gov/hmcts/sptribs/document/DocumentUtilTest.java
Respondent document management upload
https://tools.hmcts.net/jira/browse/ST-1443
=> ST-1443 Respondent document management upload

build.gradle, src/cftlib/resources/docker/cft-lib-work-allocation.yml
=> Changes For config

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrder.java
Edit Draft order main content
https://tools.hmcts.net/jira/browse/ST-1466
=> ST-1466 Edit Draft order main content

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCaseTest.java
Edit case state check
https://tools.hmcts.net/jira/browse/ST-1468
=> ST-1468 Edit case state check

src/main/java/uk/gov/hmcts/sptribs/citizen/event/CicUpdateCaseEvent.java
Date received being captured when cases submitted via document submission service
https://tools.hmcts.net/jira/browse/SNI-4118
=> St pet sn 4118  Date received being captured when cases submitted via document submission service

.github/workflows/ci.yml, build.gradle, config/owasp/suppressions.xml, src/cftlibTest/java/uk/gov/hmcts/sptribs/cftlib/action/Case.java
https://tools.hmcts.net/jira/browse/ST-1450
=> pipeline-timeout-issue

charts/sptribs-case-api/values.preview.template.yaml
PR-880 update of XUI Webapp image to use PR image with secure doc store fixes.
N/A
=> PR-880 update of XUI Webapp image to use PR image

src/cftlibTest/java/uk/gov/hmcts/sptribs/cftlib/action/Hearing.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Hearing.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/HearingJourneyTests.java
=> To fix JudgePanel details

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/State.java, src/main/java/uk/gov/hmcts/sptribs/citizen/event/CicCreateCaseEvent.java, src/main/java/uk/gov/hmcts/sptribs/citizen/event/CicSubmitCaseEvent.java, src/main/java/uk/gov/hmcts/sptribs/citizen/event/CicUpdateCaseEvent.java, src/test/java/uk/gov/hmcts/sptribs/citizen/event/CicCreateCaseEventTest.java, src/test/java/uk/gov/hmcts/sptribs/citizen/event/CicSubmitCaseEventTest.java, src/test/java/uk/gov/hmcts/sptribs/citizen/event/CicUpdateCaseEventTest.java
DSS submit backend
https://tools.hmcts.net/jira/browse/ST-1472
=> ST-1472 DSS submit backend

src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Case.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/CloseCaseTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/IssueADecisionTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/IssueFinalDecisionTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/IssueToRespondentTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/ReferCaseToJudgeTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/ReferCaseToLegalOfficerTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/StayCaseTests.java
Few of the E2E tests are failing on preview environment due to h2 heading issue with new notification on screens about services downtime. This PR is to fix those failing E2E tests.
=> fix failing E2E tests on preview

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/DssCaseData.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/DssMessage.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/sptribs/citizen/event/CicSubmitCaseEvent.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTabTest.java, src/test/java/uk/gov/hmcts/sptribs/citizen/event/CicSubmitCaseEventTest.java
DSS Messages
https://tools.hmcts.net/jira/browse/ST-1367
=> ST-1367 DSS Messages

src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTabTest.java
https://tools.hmcts.net/jira/browse/ST-1473
=> case document tab haas been removed-new

.github/workflows/ci.yml, build.gradle, config/owasp/suppressions.xml
=> Sptribs cic release 2 fix conflict

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/ApplicantDetails.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/ContactPreferenceDetails.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/RepresentativeDetails.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/SelectParties.java
https://tools.hmcts.net/jira/browse/SNI-4172
=> SNI-4172 rollback

src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerMaintainLinkCase.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/ST-464
=> Feat/st 464 Maintain Link warning page

src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/ContactPartiesTests.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerContactParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/RespondentContactParties.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerContactPartiesTest.java
Reverts hmcts/sptribs-case-api#1064 as failed removal of Contact Parties event.
=> Revert "ST-1380 XUI test"

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/RespondentContactParties.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/java/uk/gov/hmcts/sptribs/common/CommonConstants.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/ContactPartiesNotification.java, src/main/java/uk/gov/hmcts/sptribs/notification/NotificationHelper.java, src/main/java/uk/gov/hmcts/sptribs/notification/PartiesNotification.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/RespondentContactPartiesTest.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/ContactPartiesNotificationTest.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/NotificationHelperTest.java
Respondent Contact Parties notification
https://tools.hmcts.net/jira/browse/ST-1499
=> ST-1499 Respondent Contact Parties notification

src/main/java/uk/gov/hmcts/sptribs/common/CommonConstants.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/CaseFinalDecisionIssuedNotification.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/DecisionIssuedNotification.java, src/main/java/uk/gov/hmcts/sptribs/notification/NotificationHelper.java, src/main/java/uk/gov/hmcts/sptribs/notification/NotificationServiceCIC.java
=> Feat/st 1430 1: Debug Notification issue

src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Case.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/CloseCaseTests.java
=> fix e2e tests

Jenkinsfile_CNP
Switching Bundling back on for R2.1
=> Switching on Bundling for R2.1

src/main/java/uk/gov/hmcts/sptribs/controllers/DocumentManagementController.java
https://tools.hmcts.net/jira/browse/ST-1507
=> ST-1507-refactoring

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/DocumentManagementSelectDocuments.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/service/OrderService.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtil.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java, src/main/java/uk/gov/hmcts/sptribs/notification/NotificationHelper.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateDraftOrderTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrderTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrderTest.java
Seperetor change for order documents
https://tools.hmcts.net/jira/browse/ST-1430
=> ST-1430 Seperator change for order documents

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerMaintainLinkCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/LinkCaseSelectCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/PageShowConditionsUtil.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCaseTest.java
https://tools.hmcts.net/jira/browse/ST-463
=> ST-463 Maintain link

build.gradle, src/cftlib/resources/docker/cft-lib-work-allocation.yml, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerAddNote.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/access/DefaultAccess.java, src/main/resources/cftlib-am-role-assignments.json
=> Sptribs cic release 2 wa st 1265 v2

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/DssMessage.java, src/main/java/uk/gov/hmcts/sptribs/citizen/event/CicSubmitCaseEvent.java, src/test/java/uk/gov/hmcts/sptribs/citizen/event/CicSubmitCaseEventTest.java
https://tools.hmcts.net/jira/browse/ST-1367
=> ST-1367 Access problem

README.md, charts/sptribs-case-api/values.preview.template.yaml
Merging more changes from master into R2
=> Sptribs cic release 2 merge master v3

src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java
Fixing CFTLib build error
https://tools.hmcts.net/jira/browse/ST-1454
=> ST-1454 Fixing build error - removing extraneous buildMessagesTab call

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/sptribs/ciccase/search/CaseFieldsConstants.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/search/SearchInputFields.java
Added category and subcategory to the Search Input fields.
https://tools.hmcts.net/jira/browse/SNI-4173
=> SNI-4173: Added category and subcategory to the Search Input fields.

src/main/java/uk/gov/hmcts/sptribs/citizen/event/DssApplicationReceivedNotification.java
https://tools.hmcts.net/jira/browse/ST-1428
=> ST-1428 Representative Email

README.md
Noddy change to re-trigger a pipeline - latest one has sandbox nonsense again
ST-1454
=> Sptribs cic release 3 trigger pipeline

src/main/resources/application.yaml
=> Bundling url to demo

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java
Publishing Hearings: Create listing for WA - Admin Task - Complete Hearing Outcome
=> ST-1290 WA - Admin Task - Complete Hearing Outcome

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseBuilt.java
Publishing Hearings: Create listing for WA - Admin Task - Refer Case
=> ST-1275 WA Admin Task Refer Case

src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtil.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/search/CaseFieldsConstants.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/search/SearchInputFields.java, src/main/java/uk/gov/hmcts/sptribs/notification/NotificationHelper.java
https://tools.hmcts.net/jira/browse/ST-847
=> ST-847 Dynamicmultiselectlist

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrder.java
https://tools.hmcts.net/jira/browse/ST-1503
=> ST-1503-Update CaseWorkerEditDraftOrder.java

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloseTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/HearingRecordingUploadPage.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueDecisionUploadNotice.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReinstateUploadDocuments.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/SendOrderUploadOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/UploadCaseDocuments.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/CaseUploadDocuments.java
https://tools.hmcts.net/jira/browse/ST-1485
=> ST-1485-text update

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerBundleStitchComplete.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloneBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCreateBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStitchBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/search/CaseFieldsConstants.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/search/SearchInputFields.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerBundleStitchCompleteTest.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestEventConstants.java
=> Bundling new event to demo

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToLegalOfficer.java
Publishing Refer to Legal Officer Event for wa-legal-officer-task-Review-new-case-and-provide-directions-legal-officer
=> ST-1311 WA legal officer task review new case and provide directions legal officer

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerBundleStitchComplete.java
=> demo_bundling new event

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagAdditionalInfo.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseFlagTest.java
=> ST-443 Additional info message

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/FurtherDetails.java
Updated few conditions in Enter Further Details page.
https://tools.hmcts.net/jira/browse/SNI-4171
=> SNI-4171: Updated few conditions in Enter Further Details page

src/main/resources/cftlib-am-role-assignments.json
Assigning user for WA  "roleName": "senior-legal-caseworker"
=> ST-1311 Assigning user for WA

src/main/resources/cftlib-am-role-assignments.json
Correcting "roleName": "regional-centre-admin"
=> ST-1311 Correcting "roleName": "regional-centre-admin"

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCase.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseNumber.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCaseTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerMaintainLinkCaseTest.java
=> ST-1435 demo config

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerMaintainLinkCase.java
Manage case links
https://tools.hmcts.net/jira/browse/ST-463
=> ST-463 Manage case links

src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtil.java
=> ST-1435 URL check

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java
=> ST-1048 Link reason

charts/sptribs-case-api/values.yaml, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerContactParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtil.java, src/main/resources/application.yaml
=> ST-1435 document url change

src/main/java/uk/gov/hmcts/sptribs/citizen/event/CicSubmitCaseEvent.java
Publishing DSS_SUBMITTED Event
=> ST-1274-WA - Admin Task - Vet New Case Documents

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java
=> ST-1328-wa-admin-task follow up none compliance of directions

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToJudge.java, src/main/resources/cftlib-am-role-assignments.json
Publishing Refer to Judge Event and adding senior-judge Role
=> ST-1305 WA judicial task review list case within 5 days judge

src/main/resources/cftlib-am-role-assignments.json
Correcting     "roleCategory": "JUDICIAL",
=> ST 1305-wa judicial task review list case within 5 days judicial

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/UserRolesForAccessProfiles.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/accessprofile/CICAccessProfile.java
Added few more roles. Fixed the issue with displaying cases
https://tools.hmcts.net/jira/browse/ST-1106
=> ST-1106: Added few more roles. Fixed the issue with displaying cases

config/owasp/suppressions.xml
Suppressing CVE-2020-8908 - we are already on Java 7
https://tools.hmcts.net/jira/browse/ST-1548
=> Sptribs cic release 3 st 1548

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/UserRolesForAccessProfiles.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/accessprofile/CICAccessProfile.java
Removed PUI and Jrd role mappings as they are not needed. And also CCD config file import is failing due to these roles.
https://tools.hmcts.net/jira/browse/ST-1106
=> Feat/st 1106 2: Removed PUI and Jrd role mappings

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/UserRolesForAccessProfiles.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/accessprofile/CICAccessProfile.java
Added role mapping to Citizen user
https://tools.hmcts.net/jira/browse/ST-1106
=> Feat/st 1106: Added role mapping to Citizen user

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCase.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseNumber.java, src/main/java/uk/gov/hmcts/sptribs/common/links/LinkService.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCaseTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerMaintainLinkCaseTest.java
Fixing PMD code smells without affecting functionality
https://tools.hmcts.net/jira/browse/ST-1549
=> Sptribs cic release 3 st 1549

src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Case.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/LinkCaseTests.java
=> Add Link case tests

src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/CaseApiApplication.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerManageCaseFlag.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/FlagAdditionalInfo.java, src/main/java/uk/gov/hmcts/sptribs/flag/refdata/FlagTypeClient.java, src/main/java/uk/gov/hmcts/sptribs/flag/service/FlagService.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerManageCaseFlagTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/service/FlagServiceTest.java
=> ST-443 Additonal message optional

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCase.java
The search fields in case list had wrong options or some extra options , this has been fixed now and is showing right options now.
https://tools.hmcts.net/jira/browse/ST-1490
=> St-1490 smoke test, To test the search fields have correct options.

charts/sptribs-case-api/values.yaml, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/document/DocumentClient.java, src/main/resources/application.yaml
=> ST-1435 URL change

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/DssDocumentInfo.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/DssUploadedDocument.java, src/main/java/uk/gov/hmcts/sptribs/citizen/event/CicSubmitCaseEvent.java
Added Metadata for DSS Update Functionality
https://tools.hmcts.net/jira/browse/ST-1406
=> Feat/st 1406: Added Metadata for DSS Update Functionality

Jenkinsfile_CNP, charts/sptribs-case-api/values.yaml, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtil.java, src/main/resources/application.yaml
=> ST-1435 url

src/main/java/uk/gov/hmcts/sptribs/citizen/event/DssApplicationReceivedNotification.java
https://tools.hmcts.net/jira/browse/ST-1428
=> ST-1428- small fix for representation notifcation 

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCreateBundle.java
https://tools.hmcts.net/jira/browse/ST-1388
=> ST-1388 Casedocuments to payload

README.md, charts/sptribs-case-api/values.preview.template.yaml
Pointed to Preview role assignment service
=> Feat/preview issue: Pointed to Preview role assignment service

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloseTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/HearingRecordingUploadPage.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueDecisionUploadNotice.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReinstateUploadDocuments.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/SendOrderUploadOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/UploadCaseDocuments.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/CaseUploadDocuments.java
Remove documents message
https://tools.hmcts.net/jira/browse/ST-1485
=> ST-1485 Remove documents message

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/UserRolesForAccessProfiles.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/accessprofile/CICAccessProfile.java
=> ST-1048 Access profile added

src/cftlib/java/uk/gov/hmcts/sptribs/cftlib/CftLibConfig.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/UserRolesForAccessProfiles.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/accessprofile/CICAccessProfile.java
=> ST-1048 Further tweaks to userroles and access profiles

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java
Added prefix to Listing object to fix issue with populating Listing object
https://tools.hmcts.net/jira/browse/ST-1382
=> Feat/st 1382: Added prefix to Listing object

Jenkinsfile_CNP
…fix to proceed build
Update Jenkins file to disable Functional test as temporary fix. This will be revert once back.
https://tools.hmcts.net/jira/browse/ST-1406
=> ST-1406: Update Jenkins file to disable Functional test

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerMaintainLinkCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseFlag.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerManageCaseFlag.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java
https://tools.hmcts.net/jira/browse/ST-1566-
=> 1566 - labels changes

Jenkinsfile_CNP, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/citizen/event/CicDssUpdateCaseEvent.java, src/main/java/uk/gov/hmcts/sptribs/common/config/AppsConfig.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/sptribs/citizen/event/CicDssUpdateCaseEventTest.java
Added New DSS Update case event
https://tools.hmcts.net/jira/browse/ST-1406
=> Feat/st 1406: Added New DSS Update case event

renovate.json
Renovate config
https://tools.hmcts.net/jira/browse/ST-1570
=> ST-1570 Adding renovate config

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerMaintainLinkCase.java
Added few more attributes to ARGUMENT option
=> Feat/st 1051 linking: Added few more attributes to ARGUMENT option

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseFlag.java
Reverts hmcts/sptribs-case-api#1235
=> Revert "Feat/st 1048: Added supplementary_id in aboutToStart method"

src/main/java/uk/gov/hmcts/sptribs/common/event/CreateTestCase.java
https://tools.hmcts.net/jira/browse/ST-1567
=> St 1567 - Notification fail message on case creation page

build.gradle
Upgrading Tomcat to fix CVE
https://tools.hmcts.net/jira/browse/ST-1573
=> St 1573 fix CVE 2023 41080

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/DocumentManagementSelectDocuments.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtil.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java
CaseDocuments failing CollectionValidation in CCD, because no id or value elements.
Adding these by converting it to a Collection of ListValues.
=> St fix bundling list values fix

Jenkinsfile_CNP
Removing redundant method.
https://tools.hmcts.net/jira/browse/ST-1574
=> ST-1574 Fixing Jenkins warning

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/FlagDetail.java
Updated FlagDetails attribute types
=> Feat/st 1048 flags: Updated FlagDetails attribute types

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloneBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCreateBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStitchBundle.java
Adding payload logging for Bundling events
=> ST-Adding logging of payload for Bundling events.

src/main/java/uk/gov/hmcts/sptribs/common/ccd/HighLevelDataSetupApp.java
Added caseworker_admin role to HighLevelDataSetUp file
=> Feat/preview access profiles: Added caseworker_admin role to HighLevelDataSetUp file

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/FlagDetail.java, src/main/java/uk/gov/hmcts/sptribs/common/event/CreateTestCase.java, src/main/java/uk/gov/hmcts/sptribs/common/service/CcdSupplementaryDataService.java, src/test/java/uk/gov/hmcts/sptribs/common/service/CcdSupplementaryDataServiceTest.java
Enabled sending supplementary_data_request. Also changed to system user to make call to set the data.
=> Feat/st 1048 flags: Enabled sending supplementary_data_request 

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/FlagDetail.java, src/main/java/uk/gov/hmcts/sptribs/common/event/CreateTestCase.java, src/main/java/uk/gov/hmcts/sptribs/common/service/CcdSupplementaryDataService.java, src/test/java/uk/gov/hmcts/sptribs/common/service/CcdSupplementaryDataServiceTest.java
=> Feat/st 1048: Fix to set supplementary_data

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/NewOrderIssuedNotification.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerContactPartiesTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueCaseTest.java
Applying SNI-4576 changes to sptribs_cic_release_3
SNI-4576
=> SNI-4576 Applying changes to sptribs_cic_release_3

src/test/java/uk/gov/hmcts/sptribs/common/notification/NewOrderIssuedNotificationTest.java
Test fixed as master is merged
=> test fixed

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloseTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseConsentOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseRejectionDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseRule27.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseStrikeOutDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseWithdrawalDetails.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CloseCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CloseReason.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/State.java, src/main/java/uk/gov/hmcts/sptribs/recordlisting/LocationClient.java, src/main/java/uk/gov/hmcts/sptribs/recordlisting/LocationService.java, src/test/java/uk/gov/hmcts/sptribs/recordlisting/LocationServiceTest.java
Close case Rule 27 and Fixed Region data issue
https://tools.hmcts.net/jira/browse/ST-1262
=> Feat/st 1262 master: Close case Rule 27 and Fixed Region data issue

build.gradle, charts/sptribs-case-api/values.yaml, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerMaintainLinkCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCaseTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerMaintainLinkCaseTest.java
=> Feat/st 1051 Fix for Case Linking

.github/renovate.json, renovate.json
=> ST-1388 Fixing renovate config

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/service/OrderService.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateDraftOrderTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrderTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/service/OrderServiceTest.java
Resolve duplicate order documents on case file view
https://tools.hmcts.net/jira/browse/SNI-4699
=> SNI-4699: Fix - Order documents on CFV being duplicated

src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java, src/main/java/uk/gov/hmcts/sptribs/common/event/CreateTestCase.java
Setting caseNameHmctsInternal field required for Case Linking
=> ST-1051: Setting caseNameHmctsInternal field

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerIssueDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloseTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecision.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/helper/RecordListHelper.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/CaseFinalDecisionIssuedNotification.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/CaseReinstatedNotification.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/CaseWithdrawnNotification.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/DecisionIssuedNotification.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/ListingCreatedNotification.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCloseTheCaseTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueDecisionTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerIssueFinalDecisionTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListingTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/ReinstateCaseTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/helper/RecordListHelperTest.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/CaseFinalDecisionIssuedNotificationTest.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/CaseReinstatedNotificationTest.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/CaseWithdrawnNotificationTest.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/DecisionIssuedNotificationTest.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/ListingCreatedNotificationTest.java
Application notifications
https://tools.hmcts.net/jira/browse/ST-1598
=> ST-1598 Applicant emails fixes

charts/sptribs-case-api/Chart.yaml
Moving to non Docker
https://tools.hmcts.net/jira/browse/DTSPO-14561
https://tools.hmcts.net/jira/browse/DTSPO-14561
https://tools.hmcts.net/jira/browse/ST-1610
=> St 1610 fix docker problem

charts/sptribs-case-api/Chart.yaml
Fixing ACR problem
https://tools.hmcts.net/jira/browse/ST-1610
=> St1610 fixing acr problem wa

charts/sptribs-case-api/Chart.yaml
Fixing ACR Docker problem
https://tools.hmcts.net/jira/browse/ST-1610
=> ST-1610 Chart changes to fix Docker problem

src/main/resources/application.yaml
Setting Contact Parties to true for Release.
=> ST- Enabling contact parties on PROD.

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerLinkCaseTest.java
https://tools.hmcts.net/jira/browse/ST-792
=> ST-792 :  Case Linked

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseFlag.java
Removed EventNotes to Case Flags
=> Feat/st 1048 flags: Removed EventNotes to Create Case Flags

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerMaintainLinkCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerMaintainLinkCaseTest.java
https://tools.hmcts.net/jira/browse/ST-824
=> ST-824 : Case Unlinked (CIC)

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditHearingSummary.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditRecordListing.java
ST-1290 publishing Hearings: Edit Listing and Hearings: Edit Summary Event
=> ST-1290-WA-admin-task-complete-hearing-outcome

charts/sptribs-case-api/values.aat.template.yaml, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrderTest.java
Remove toggles after testing in AAT
https://tools.hmcts.net/jira/browse/SNI-4754
=> SN-4754: Remove toggles after testing in AAT

src/cftlib/java/uk/gov/hmcts/sptribs/cftlib/CftLibConfig.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/UserRole.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/access/CitizenAccess.java, src/main/java/uk/gov/hmcts/sptribs/citizen/event/CicSubmitCaseEvent.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/model/access/CitizenAccessTest.java
Added new role caseworker-update-dss-application for dss update case
https://tools.hmcts.net/jira/browse/ST-1638
=> ST-1638 Added new role caseworker-update-dss-application for dss update case

Jenkinsfile_CNP, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml
SEtting CONTACT_PARTIES_FEATURE to true
https://tools.hmcts.net/jira/browse/ST-1606
=> ST-1606 Setting CONTACT_PARTIES_FEATURE to true.

config/owasp/suppressions.xml
Suppress CVE-2023-42794, CVE-2023-42795, CVE-2023-45648
=> Suppress CVE-2023-42794, CVE-2023-42795, CVE-2023-45648

Jenkinsfile_CNP, config/owasp/suppressions.xml
Resolved merged conflicts from master
=> Resolved merged conflicts from master

src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/ContactPartiesTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/EditCicaCaseDetailsTests.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/enums/Actions.java
This PR is to add CICA edit case details E2E test and fix-enable contact parties E2E test
No Jira
=> Add cica edit case details e2e test and fix-enable contact parties e2e test

build.gradle, config/owasp/suppressions.xml
… Link date issue
Pointing to updated ccd-config-generator version to fix Case
https://tools.hmcts.net/jira/browse/ST-1640
=> ST-1640: Case Linking date issue

config/owasp/suppressions.xml
Suppress CVE-2023-5072, CVE-2023-44487
=> Suppress CVE-2023-5072, CVE-2023-44487

Jenkinsfile_CNP, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/resources/application.yaml
Switching Case Flags on for AAT
=> ST-1048 Turning CaseFlags On for AAT.

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerContactParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/RespondentContactParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtil.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtilTest.java
https://tools.hmcts.net/jira/browse/ST-1645
=> St 1645: removing mp3 files from contact parties

src/main/java/uk/gov/hmcts/sptribs/common/notification/CancelHearingNotification.java
=> ST-1581 Adding missing sendToApplicant method.

src/test/java/uk/gov/hmcts/sptribs/common/notification/CancelHearingNotificationTest.java
Adding unit tests for CancelHearingNotification to Applicant.
=> ST-1567 Adding tests for Applicant Cancel Hearing notification

src/main/java/uk/gov/hmcts/sptribs/common/event/CreateTestCase.java
Using CollectionUtils as it's null-safe
=> ST-1567 Using CollectionUtils to cater for null sets.

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCaseTest.java
fix for case flags missing in edit case
https://tools.hmcts.net/jira/browse/ST-1662
=> st-1662 - fix for case flags missing in edit case

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerContactParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/CheckRequiredUtil.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventUtil.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerContactPartiesTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCaseTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/CheckRequiredUtilTest.java
fix for bug st-1660 st-1661
https://tools.hmcts.net/jira/browse/ST-1661
https://tools.hmcts.net/jira/browse/ST-1660
=> fix for bug st-1660 st-1661

src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java
Flagging off Bundling tab for CaseTypesTab.
=> ST- Flagging buildBundlesTab off.

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java
Removing redundant field for Police Authority
https://tools.hmcts.net/jira/browse/ST-1382
=> ST-1382 Remove Police Authority field from CicCase

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ContactPartiesSelectDocument.java
=> text fix for contact parties

README.md, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/RetiredFields.java
ST-1382
reversing retired fields
=> St 1382 reversing retired fields

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToLegalOfficer.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/ReferToLegalOfficerAdditionalInfo.java
=> WA-task-creation for legal ops

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/UserRole.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/access/CaseworkerAndSuperUserAccess.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/model/access/CaseworkerAndSuperUserAccessTest.java
=> ST-1382 Adding some access role and access changes.

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagement.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDssUpdateCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/RespondentDocumentManagement.java
=> Publishing Events

src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtil.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtilTest.java
https://tools.hmcts.net/jira/browse/ST-1651
=> ST-1651- Manage documents shows URL

src/main/java/uk/gov/hmcts/sptribs/judicialrefdata/JudicialClient.java, src/main/java/uk/gov/hmcts/sptribs/judicialrefdata/JudicialService.java, src/test/java/uk/gov/hmcts/sptribs/judicialrefdata/JudicialServiceTest.java
Fix calls to JRD /refdata/judicial/users API endpoint
=> Fix calls to JRD API

src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/common/config/ControllerConstants.java, src/main/java/uk/gov/hmcts/sptribs/judicialrefdata/JudicialClient.java, src/main/java/uk/gov/hmcts/sptribs/judicialrefdata/JudicialService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/sptribs/judicialrefdata/JudicialServiceTest.java
Enable toggle for JRD API so we can move from v1 to v2 as required
=> Enable toggle for JRD API so we can move from v1 to v2 as required

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerContactParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/RespondentContactParties.java
https://tools.hmcts.net/jira/browse/ST-1660
=> ST 1660 - persistent message field fixed

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerContactParties.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/RespondentContactParties.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/ContactPartiesNotification.java, src/main/java/uk/gov/hmcts/sptribs/notification/NotificationHelper.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/ContactPartiesNotificationTest.java
https://tools.hmcts.net/jira/browse/ST-1644
=> St 1644 - contact parties fix

build.gradle, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Case.java
This PR fixes the issue with cross-browser E2E tests on master nightly pipeline
=> Fix case api cross-browser e2e tests on master nightly pipeline

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToJudge.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToLegalOfficer.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/ReferToJudge.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/ReferToLegalOfficer.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToJudgeTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToLegalOfficerTest.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTabTest.java
Reverts hmcts/sptribs-case-api#1509
=> Revert "SNI-4951: Case referrals related changes"

src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Case.java, src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Login.java
This PR updates e2e tests to fix failing tests
=> Update e2e tests to fix flakiness

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToJudge.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToLegalOfficer.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/ReferToJudge.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/ReferToLegalOfficer.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToJudgeTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToLegalOfficerTest.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTabTest.java
https://tools.hmcts.net/jira/browse/SNI-4951
=> SNI-4951: Case referrals related changes

config/owasp/suppressions.xml
suppressing CVE to allow R3 pipeline to run.
=> ST-1688 Suppressing new CVE for Bouncycastle.

build.gradle, config/fortify-client.properties
Fortify fixes
https://tools.hmcts.net/jira/browse/ST-1496
=> ST-1496: Fix fortify issues

config/owasp/suppressions.xml
Suppressing CVE to enable pipelines to succeed. 
Looks like logback is an external dependency, so might need to be upgraded somewhere else - CCD?
=> ST-1388 Suppressing logback CVE-2023-6378 - an external dependency

src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java
Hiding this field as it should not be displayed in Linked Cases
https://tools.hmcts.net/jira/browse/ST-1695
=> ST-1695: Hiding caseName displayed in Linked Cases

Dockerfile
restriction added
https://tools.hmcts.net/jira/browse/ST-1700
=> ST-1700: Fixed fortify issue reported on docker file

charts/sptribs-case-api/values.preview.template.yaml
fixed
https://tools.hmcts.net/jira/browse/DTSSTCI-115
=> DTSSTCI-115: Enable metadata creation in CDAM for preview env while uploading a document

build.gradle, src/e2eTests/java/uk/gov/hmcts/sptribs/testutils/StringHelpers.java
This PR:
1. Fixes the failing DSS e2e tests on CI
2. Remove dependency on msedge installation for running tests on msedge in CI nightly pipeline.
=> [ST-1079] Fix dss e2e tests

Jenkinsfile_CNP
=> ST-1051 Commenting out e2eTests

Jenkinsfile_CNP, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/UserRole.java, src/main/resources/application.yaml
Unshuttering post Case Flags and Case Linking release: successful i.e. Happy Path
=> St 1051 - Unshuttering after migration

Jenkinsfile_CNP
Setting feature flag on for DSS
=> ST enabling DSS frontend feature

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/java/uk/gov/hmcts/sptribs/common/CommonConstants.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/ContactPartiesNotification.java, src/main/java/uk/gov/hmcts/sptribs/notification/NotificationHelper.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/ContactPartiesNotificationTest.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/NotificationHelperTest.java
Moved Tribunal fields to Constants - Fix migrate tasks issue in Perftest
=> Moved Tribunal fields to Constants - Fix migrate tasks issue

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/NotificationResponse.java
=> SPTRIBS - Grant CitizenAccess

Jenkinsfile_CNP, src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerBundleStitchComplete.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloneBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCreateBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStitchBundle.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/tab/CaseTypeTab.java, src/main/resources/application.yaml
Bundling Toggles - Create, Edit, Clone and Stitch
https://tools.hmcts.net/jira/browse/ST-1714
=> Feat/st 1714 Bundling Toggles

src/main/java/uk/gov/hmcts/sptribs/document/bundling/client/BundlingService.java
Fix for IndexOutOfBounds exception
https://tools.hmcts.net/jira/browse/ST-1714
=> Bundling fix Exception

Jenkinsfile_CNP
Bundling update event access - Toggled ON
https://tools.hmcts.net/jira/browse/ST-1714
=> Bundling update event access - Toggled ON

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToJudge.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToLegalOfficer.java
Added Judge and Senior-Judge permissions to Refer event
https://tools.hmcts.net/jira/browse/ST-1696
=> St 1696: Updated Refer event permissions

src/main/java/uk/gov/hmcts/sptribs/document/bundling/client/BundlingService.java
Response logging and some code refactoring
https://tools.hmcts.net/jira/browse/ST-1715
=> St 1715 Bundling issue

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStitchBundle.java, src/main/java/uk/gov/hmcts/sptribs/document/bundling/BundlingConstants.java, src/main/java/uk/gov/hmcts/sptribs/document/bundling/client/BundlingService.java, src/test/java/uk/gov/hmcts/sptribs/document/bundling/BundlingServiceTest.java
Fix for exception with Stitch Bundle document
https://tools.hmcts.net/jira/browse/ST-1715
=> St 1715 Fix for exception with Stitch Bundle document

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStitchBundle.java, src/main/java/uk/gov/hmcts/sptribs/document/bundling/client/BundlingService.java
Remove redundant Bundle Folders and removed permissions to Stitch Bundle event
https://tools.hmcts.net/jira/browse/ST-1717
=> St 1717: Remove redundant Bundle Folders

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToJudge.java
Removed Judge and Senior Judge permissions for ReferToJudge event
https://tools.hmcts.net/jira/browse/ST-1696
=> St 1696 Refer to Judge Event permissions Change

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementRemove.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementRemoveTest.java
documents deleted
https://tools.hmcts.net/jira/browse/SNI-5213
=> SNI-5213: Delete documents from case file view

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerBundleStitchComplete.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStitchBundle.java, src/main/java/uk/gov/hmcts/sptribs/document/bundling/client/BundlingService.java
Enable Async stitching event to check Bundling issue
https://tools.hmcts.net/jira/browse/ST-1717
=> St 1717 Enable Async stitching event to check Bundling issue

src/main/resources/application.yaml
Enabled Security Classification flag in application yaml
https://tools.hmcts.net/jira/browse/ST-1719
=> ST-1719: Enabled Security Classification flag

charts/sptribs-case-api/values.preview.template.yaml, src/main/resources/application.yaml
Fix for api-gw pod crashing issue in Preview env
https://tools.hmcts.net/jira/browse/ST-1719
=> St 1719: Fix for api-gw pod crashing issue in Preview env

src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Login.java
I have missed to update e2e login methods properly while fixing the styling issues on my previous PR https://github.com/hmcts/sptribs-case-api/pull/1646. This is causing 4 tests to fail on the pipeline
This PR fixes the issue.
=> ST-1079: update e2e test login methods

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToJudge.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/accessprofile/CICAccessProfile.java
Access Management changes in Release 2/2.1 branch
https://tools.hmcts.net/jira/browse/ST-1106
https://tools.hmcts.net/jira/browse/ST-1696
https://tools.hmcts.net/jira/browse/ST-1719
=> Access Management changes in Release 2/2.1 branch

bin/generate-ccd-definition.sh, build.gradle
fixed
https://tools.hmcts.net/jira/browse/DTSSTCI-284
=> DTSSTCI-284: Fixed create case issue

src/main/java/uk/gov/hmcts/sptribs/document/model/CICDocument.java, src/main/java/uk/gov/hmcts/sptribs/document/model/CaseworkerCICDocument.java, src/main/java/uk/gov/hmcts/sptribs/document/model/EdgeCaseDocument.java, src/test/java/uk/gov/hmcts/sptribs/document/model/CICDocumentTest.java, src/test/java/uk/gov/hmcts/sptribs/document/model/CaseworkerCICDocumentTest.java
Fix for document types, Added .mp, .msg and .eml file types.
https://tools.hmcts.net/jira/browse/ST-1726
=> ST-1726: Fix for document types

Jenkinsfile_CNP
This PR is to disable the Case API e2e tests for shuttering. Functionality does not work for the users with shuttering and hence disabling the tests. These tests will be enabled with the unshuttering PR.
=> [ST-1079]: disable e2e tests for shuttering

Jenkinsfile_CNP
This PR is to enable e2e tests
=> [ST-1079]: enable e2e tests

src/functionalTest/resources/responses/response-caseworker-send-order-about-to-submit.json, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrder.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CicCase.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/NewOrderIssuedNotification.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/NewOrderIssuedNotificationTest.java
Added JsonIgnore to remove duplicate file in Case File View after Send Order.
https://tools.hmcts.net/jira/browse/ST-1728
=> Fix for duplicate file in Case File View post Send Order event

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerChangeSecurityClassification.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/ContactPartiesAllowedFileTypes.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/SecurityClassification.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtil.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/common/event/CreateTestCase.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerChangeSecurityClassificationTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerContactPartiesTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/util/DocumentListUtilTest.java
Changing SecurityClass to SecurityClassification
Changing model of ContactParties allowed fileTypes to check against an enum of allowed fileTypes
https://tools.hmcts.net/jira/browse/ST-1645
=> St 1645 include certain allowed filetypes

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/RespondentPartiesToContact.java
Fix for Respondent Contact Parties Notification
https://tools.hmcts.net/jira/browse/ST-1729
=> Fix for Respondent Contact Parties Notification

Jenkinsfile_CNP, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/UserRole.java
Shuttering Sptribs for R2/2.1 release.
R2/2.1
=> ST-1713 Shuttering release for R2/2.1

Jenkinsfile_CNP
Flag document management to true
ST-1713
=> ST-1713 Flagging document management to true

src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/judicialrefdata/JudicialClient.java, src/main/java/uk/gov/hmcts/sptribs/judicialrefdata/JudicialService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/sptribs/judicialrefdata/JudicialServiceTest.java
Remove elinks v2 feature toggles after successful release
https://tools.hmcts.net/jira/browse/DTSSTCI-333
=> DTSSTCI-333

src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Case.java
Small selector error, fixed.
[DTSSTCI-397](https://tools.hmcts.net/jira/browse/DTSSTCI-397)
=> Fixing E2E pipeline

src/main/java/uk/gov/hmcts/sptribs/document/model/CICDocument.java, src/main/java/uk/gov/hmcts/sptribs/document/model/CaseworkerCICDocument.java, src/test/java/uk/gov/hmcts/sptribs/document/model/CICDocumentTest.java, src/test/java/uk/gov/hmcts/sptribs/document/model/CaseworkerCICDocumentTest.java
done
https://tools.hmcts.net/jira/browse/DTSSTCI-378
=> DTSSTCI-378: Do not support msg and eml files

charts/sptribs-case-api/Chart.yaml, charts/sptribs-case-api/values.yaml, src/main/resources/application.yaml
Add sptribs_dss_update_case_web to S2S_AUTHORISED_SERVICES
(sptribs-case-api-dot-env secret value in vault also updated to reflect this change)
https://tools.hmcts.net/jira/browse/DTSSTCI-413
=> DTSSTCI-413

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/State.java
Add subject full name above Case number
[https://tools.hmcts.net/jira/browse/DTSSTCI-235](url)
=> DTSSTCI-235 - Add subject full name above Case number

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerDocumentManagementRemove.java
Add Ready To List state to caseworker-remove-document and tidy up duplicate role permissions
https://tools.hmcts.net/jira/browse/DTSSTCI-570
=> DTSSTCI-570

src/main/java/uk/gov/hmcts/sptribs/services/ccd/CaseApiService.java
Resolve incorrect event for update case enum
https://tools.hmcts.net/jira/browse/DTSSTCI-357
=> DTSSTCI-357

charts/sptribs-case-api/Chart.yaml, charts/sptribs-case-api/values.yaml
https://tools.hmcts.net/jira/browse/DTSSTCI-396
Remove autoscaling config from app and into flux
=> DTSSTCI-396

charts/sptribs-case-api/Chart.yaml, charts/sptribs-case-api/values.yaml
Enable spot instances by default in values yaml
https://tools.hmcts.net/jira/browse/DTSSTCI-395
=> DTSSTCI-395

src/main/java/uk/gov/hmcts/sptribs/controllers/DocumentManagementController.java, src/main/java/uk/gov/hmcts/sptribs/services/cdam/CaseDocumentApiService.java, src/main/resources/application.yaml
=> Add logging for dss update document upload issue

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/State.java
Ensure CICA users can view cases which have the status 'Ready to list'
https://tools.hmcts.net/jira/browse/DTSSTCI-505
=> DTSSTCI-505 - Ensure CICA users can view cases which have the status 'Ready to list'

build.gradle, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerHearingOptionsIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/controllers/CaseManagementControllerIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/controllers/DocumentManagementControllerIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/controllers/RootControllerIT.java, src/integrationTest/resources/citizen-create-case-response.json, src/integrationTest/resources/citizen-document-upload-response.json, src/main/java/uk/gov/hmcts/sptribs/caseworker/util/EventConstants.java, src/main/java/uk/gov/hmcts/sptribs/exception/CaseCreateOrUpdateException.java, src/main/java/uk/gov/hmcts/sptribs/services/ccd/CaseApiService.java
Create integration tests for controllers module
https://tools.hmcts.net/jira/browse/DTSSTCI-362
=> DTSSTCI-362

src/functionalTest/java/uk/gov/hmcts/sptribs/systemupdate/event/SystemMigrateCaseFlagsFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/systemupdate/event/SystemMigrateCaseLinksFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/systemupdate/event/SystemMigrateOldHearingFT.java, src/functionalTest/resources/request/casedata/ccd-callback-casedata-system-migrate-case-flags-about-to-submit.json, src/functionalTest/resources/request/casedata/ccd-callback-casedata-system-migrate-old-hearing-about-to-submit.json, src/functionalTest/resources/request/casedata/ccd-callback-system-migrate-case-links-about-to-submit.json, src/functionalTest/resources/responses/response-system-migrate-case-flags-about-to-submit.json, src/functionalTest/resources/responses/response-system-migrate-case-links-about-to-submit.json, src/functionalTest/resources/responses/response-system-migrate-old-hearing-about-to-submit.json, src/main/java/uk/gov/hmcts/sptribs/caseworker/service/HearingService.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/RetiredFields.java, src/main/java/uk/gov/hmcts/sptribs/systemupdate/event/SystemMigrateCase.java, src/test/java/uk/gov/hmcts/sptribs/systemupdate/event/SystemMigrateCaseTest.java
Add functional tests from system update events
https://tools.hmcts.net/jira/browse/DTSSTCI-694
=> DTSSTSCI-694

Jenkinsfile_CNP, Jenkinsfile_nightly
Making the E2E tests run on the nightly pipeline instead of master by default.
https://tools.hmcts.net/jira/browse/DTSSTCI-762
=> DTSSTCI762 - Swap jenkinsfiles

Jenkinsfile_nightly
Hotfix for the E2E nightly tests due to failures
=> Fix nightly E2E tests to use custom E2E step

src/e2eTests/java/uk/gov/hmcts/sptribs/e2e/Case.java
Fix for selectors in Create Case document upload
https://tools.hmcts.net/jira/browse/DTSSTCI-850
=> DTSSTCI-850 - E2E fix

src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseStay.java
Correct label for case stay text box when other selected
https://tools.hmcts.net/jira/browse/DTSSTCI-859
=> DTSSTCI-859

src/functionalTest/resources/responses/response-caseworker-edit-record-listing-about-to-start.json, src/functionalTest/resources/responses/response-caseworker-hearing-options-about-to-start.json, src/integrationTest/resources/caseworker-hearing-options-about-to-start-response.json, src/main/java/uk/gov/hmcts/sptribs/recordlisting/LocationService.java
Filter out NI and National from region list
https://tools.hmcts.net/jira/browse/DTSSTCI-753
=> DTSSCI-753

src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/services/ccd/CaseApiService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/sptribs/services/ccd/CaseApiServiceTest.java
Remove feature toggle for update case fix
(TO BE MERGED AFTER SUCCESSFUL COMPLETION OF UPDATE CASE RELEASE)
https://tools.hmcts.net/jira/browse/DTSSTCI-861
=> DTSSTCI-861

build.gradle, src/functionalTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerEditHearingSummaryFT.java, src/functionalTest/resources/request/casedata/ccd-callback-casedata-caseworker-create-hearing-summary-about-to-submit.json, src/functionalTest/resources/request/casedata/ccd-callback-casedata-caseworker-edit-hearing-summary-about-to-submit.json, src/functionalTest/resources/request/casedata/ccd-callback-casedata-caseworker-edit-record-listing-about-to-submit.json, src/functionalTest/resources/request/casedata/ccd-callback-casedata-caseworker-edit-record-listing-no-parties-about-to-submit.json, src/functionalTest/resources/request/casedata/ccd-callback-casedata-edit-hearing-summary-select-mid-event.json, src/functionalTest/resources/responses/response-caseworker-create-hearing-summary-about-to-submit.json, src/functionalTest/resources/responses/response-caseworker-edit-hearing-summary-about-to-start.json, src/functionalTest/resources/responses/response-caseworker-edit-hearing-summary-about-to-submit.json, src/functionalTest/resources/responses/response-caseworker-edit-hearing-summary-select-mid-event.json, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerCreateHearingSummaryIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerEditHearingSummaryIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerPostponeHearingIT.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCreateHearingSummary.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditHearingSummary.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCancelHearing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerPostponeHearing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/EditHearingSummarySelect.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/service/HearingService.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCreateHearingSummaryTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditHearingSummaryTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditRecordListingTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerPostponeHearingTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/page/EditHearingSummarySelectTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/service/HearingServiceTest.java
Stop duplicates of files uploaded in hearing summary events
https://tools.hmcts.net/jira/browse/DTSSTCI-838
=> DTSSTCI-838

src/functionalTest/java/uk/gov/hmcts/sptribs/citizen/event/CicDssUpdateCaseEventFT.java, src/functionalTest/resources/responses/response-dss-update-case-submission-about-to-submit.json, src/main/java/uk/gov/hmcts/sptribs/citizen/event/CicDssUpdateCaseEvent.java, src/test/java/uk/gov/hmcts/sptribs/citizen/event/CicDssUpdateCaseEventTest.java
Add date uploaded for any docs added through update case
https://tools.hmcts.net/jira/browse/DTSSTCI-864
=> DTSSTCI-864

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/CloseCaseConsentOrder.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CloseReason.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/State.java, src/main/java/uk/gov/hmcts/sptribs/common/CommonConstants.java, src/main/java/uk/gov/hmcts/sptribs/common/notification/CaseWithdrawnNotification.java, src/test/java/uk/gov/hmcts/sptribs/common/notification/CaseWithdrawnNotificationTest.java
Add death of appellant as close case reason
https://tools.hmcts.net/jira/browse/DTSSTCI-865
=> DTSSTCI-865

build.gradle, src/contractTest/java/uk.gov.hmcts.sptribs/IdamConsumerTest.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/ExtendedCaseDetails.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/HearingDate.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/HearingSession.java, src/main/java/uk/gov/hmcts/sptribs/common/config/jackson/JacksonConfiguration.java, src/test/java/uk/gov/hmcts/sptribs/citizen/event/CicCreateCaseEventTest.java, src/test/java/uk/gov/hmcts/sptribs/citizen/event/CicSubmitCaseEventTest.java, src/test/java/uk/gov/hmcts/sptribs/citizen/event/CicUpdateCaseEventTest.java, src/test/java/uk/gov/hmcts/sptribs/controllers/CaseManagementControllerTest.java, src/test/java/uk/gov/hmcts/sptribs/controllers/DocumentManagementControllerTest.java, src/test/java/uk/gov/hmcts/sptribs/exception/CaseCreateOrUpdateExceptionTest.java, src/test/java/uk/gov/hmcts/sptribs/exception/DocumentUploadOrDeleteExceptionTest.java, src/test/java/uk/gov/hmcts/sptribs/services/CaseManagementServiceTest.java, src/test/java/uk/gov/hmcts/sptribs/services/DocumentManagementServiceTest.java, src/test/java/uk/gov/hmcts/sptribs/services/ccd/CaseApiServiceTest.java, src/test/java/uk/gov/hmcts/sptribs/services/cdam/CaseDocumentApiServiceTest.java, src/test/java/uk/gov/hmcts/sptribs/services/cdam/DssCaseDocumentClientTest.java, src/test/java/uk/gov/hmcts/sptribs/testutil/AppsUtilTest.java
This reverts commit 070f117689cf0f8936d19f79598a29314651ef13.
https://tools.hmcts.net/jira/browse/DTSSTCI-908
=> Revert "DTSSTCI-908: Combined all Renovate PR changes as of 9th july

src/main/resources/dmn/wa-task-cancellation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/dmn/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/main/resources/dmn/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/main/resources/dmn/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/dmn/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/main/resources/dmn/wa-task-types-st_cic-criminalinjuriescompensation.dmn
Added TTL
https://tools.hmcts.net/jira/browse/DTSSTCI-896
=> Dtsstci 896: Add TTL

src/functionalTest/resources/application.yaml, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/sptribs/systemupdate/schedule/migration/SystemMigrateGlobalSearchTask.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/sptribs/systemupdate/schedule/migration/SystemMigrateGlobalSearchFieldsTaskTest.java
Configure global search task for testing
https://tools.hmcts.net/jira/browse/DTSSTCI-191
=> DTSSTCI-191

Jenkinsfile_CNP
Remove withTeamSecrets method call as not required and causing errors
https://tools.hmcts.net/jira/browse/DTSSTCI-916
=> DTSSTCI-916

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/ExtendedCaseDetails.java
Reverted
https://tools.hmcts.net/jira/browse/DTSSTCI-908
=> DTSSTCI-908: Removing unwanted data classification change

src/main/resources/dmn/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskWaInitiationTest.java
Update task initiation DMN for Issue Decision Notice to have Post State of Awaiting Outcome.
https://tools.hmcts.net/jira/browse/DTSSTCI-925 
=> [DTSSTCI-925] Update initiation DMN for Hearing: Create Summary

src/main/resources/dmn/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskWaInitiationTest.java
Update referral reason: `Time Extension request` -> `Time extension request`
https://tools.hmcts.net/jira/browse/DTSSTCI-927
=> [DTSSTCI-927] Update Review Time extention request - Judge task

src/main/resources/dmn/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskWaInitiationTest.java
Update DMN task post state: `CaseManagement` -> `AwaitingHearing`
https://tools.hmcts.net/jira/browse/DTSSTCI-926
=> [DTSSTCI-926] Update Process Postponement Directions task

src/main/resources/dmn/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmnutils/CamundaTaskConstants.java
Update configuration DMN - dueDateNonWorkingCalendar value
https://tools.hmcts.net/jira/browse/DTSSTCI-922
=> DTSSTCI-922

src/main/resources/dmn/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskWaConfigurationTest.java
Update the links for Next Steps for Register New Case Task
https://tools.hmcts.net/jira/browse/DTSSTCI-940
=> [DTSSTCI-940] Update description link for Register New Case

src/main/resources/dmn/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskWaConfigurationTest.java
Update Next Steps - issueCaseToRespondent Task
https://tools.hmcts.net/jira/browse/DTSSTCI-942
=> [DTSSTCI-942] Update Next Steps - issueCaseToRespondent Task

src/integrationTest/java/uk/gov/hmcts/sptribs/common/event/CreateCaseIT.java, src/integrationTest/resources/caseworker-create-case-about-to-submit-response.json, src/main/java/uk/gov/hmcts/sptribs/common/notification/ApplicationReceivedNotification.java
Create integration tests for Caseworker Create Case event
https://tools.hmcts.net/jira/browse/DTSSTCI-962
=> DTSSTCI-962

src/functionalTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerCaseBuiltFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerCaseFlagFT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerCaseBuiltIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerCaseFlagIT.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseBuilt.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseFlag.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerCaseBuiltTest.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseFlagTest.java
Add integration tests for CaseworkerCaseFlag and CaseworkerCaseBuilt
https://tools.hmcts.net/jira/browse/DTSSTCI-974
=> DTSSTCI-974

src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerChangeSecurityClassificationIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/CaseworkerCreateBundleIT.java, src/integrationTest/resources/application.yaml, src/integrationTest/resources/caseworker-change-security-classification-about-to-submit-response.json, src/integrationTest/resources/caseworker-create-bundle-about-to-submit-response.json, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerChangeSecurityClassification.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestConstants.java
Add integration tests for:
- CaseworkerChangeSecurityClassification
- CaseworkerCreateBundle
https://tools.hmcts.net/jira/browse/DTSSTCI-975
=> DTSSTCI-975

Jenkinsfile_CNP
Update demo environment to add WA Publish flag in definition file.
https://tools.hmcts.net/jira/browse/DTSSTCI-945
=> Enable WA feature for demo definition file

src/main/java/uk/gov/hmcts/sptribs/systemupdate/schedule/migration/SystemClearInactiveDssDraftCasesTask.java, src/test/java/uk/gov/hmcts/sptribs/systemupdate/schedule/migration/SystemClearInactiveDssDraftCasesTaskTest.java
Fix date filter as lte is used for dates further in the past or equal to the date passed to the filter
https://tools.hmcts.net/jira/browse/DTSSTCI-921
=> DTSSTCI-921

src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCaseIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCicaCaseDetailsIT.java, src/integrationTest/resources/responses/caseworker-edit-case-about-to-submit-response.json, src/integrationTest/resources/responses/caseworker-edit-cica-case-details-about-to-submit-response.json, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditCase.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestDataHelper.java
https://tools.hmcts.net/jira/browse/DTSSTCI-979
=> DTSSTCI-979: Added integration tests for Caseworker edit cases

src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditDraftOrderIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditHearingSummaryIT.java, src/integrationTest/resources/responses/caseworker-edit-draft-order-response.json, src/integrationTest/resources/responses/caseworker-edit-hearing-summary-about-to-start-response.json, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerEditHearingSummary.java, src/test/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditHearingSummaryTest.java
Add integration tests for CaseWorkerEditDraftOrder and CaseWorkerEditHearingSummary
https://tools.hmcts.net/jira/browse/DTSSTCI-980
=> DTSSTCI-980

src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/event/page/ContactPartiesSelectDocumentIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/event/page/DocumentManagementSelectDocumentsIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/event/page/EditHearingSummarySelectIT.java, src/integrationTest/resources/responses/document-management-select-document-mid-event-response.json, src/integrationTest/resources/responses/edit-hearing-summary-select-mid-event-response.json, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/DocumentManagementSelectDocuments.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestConstants.java
Add tests for:
- EditHearingSummarySelect
- ContactPartiesSelectDocument
- DocumentManagementSelectDocuments
https://tools.hmcts.net/jira/browse/DTSSTCI-990
=> DTSSTCI-990

src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/event/page/HearingRecordingUploadPageIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/event/page/HearingVenuesIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/event/page/IssueCaseSelectDocumentIT.java, src/integrationTest/resources/responses/hearing-recording-upload-page-mid-event-response.json, src/integrationTest/resources/responses/hearing-venues-mid-event-response.json, src/integrationTest/resources/responses/issue-case-select-document-mid-event-response.json, src/test/java/uk/gov/hmcts/sptribs/testutil/TestConstants.java
Add integration tests for HearingRecordingUploadPage, HearingVenues and IssueCaseSelectDocument pages.
https://tools.hmcts.net/jira/browse/DTSSTCI-991
=> DTSSTCI-991

src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerSendOrderIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStayTheCaseIT.java, src/integrationTest/resources/responses/caseworker-send-order-about-to-submit-response.json
Add integration tests for
- CaseworkerSendOrder
- CaseworkerStayTheCase
https://tools.hmcts.net/jira/browse/DTSSTCI-988
=> DTSSTCI-988

src/main/resources/dmn/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskWaConfigurationTest.java
Update next steps description to match Case: Edit case. Unblock testing in [DTSSTCI-1010](https://tools.hmcts.net/jira/browse/DTSSTCI-1010)
=> Update next steps description to match Case: Edit case

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToJudge.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseWorkerReferToLegalOfficer.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerAddNote.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCancelHearing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCaseFlag.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCloseTheCase.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerCreateBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditBundle.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerEditRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerPostponeHearing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRemoveStay.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerStayTheCase.java, src/main/java/uk/gov/hmcts/sptribs/common/ccd/HighLevelDataSetupApp.java, src/main/java/uk/gov/hmcts/sptribs/common/event/page/CaseUploadDocuments.java, src/main/java/uk/gov/hmcts/sptribs/common/service/task/SetStateAfterSubmission.java, src/main/java/uk/gov/hmcts/sptribs/document/CaseDataDocumentService.java, src/main/java/uk/gov/hmcts/sptribs/document/DocAssemblyService.java, src/main/java/uk/gov/hmcts/sptribs/document/DocumentClient.java, src/main/java/uk/gov/hmcts/sptribs/notification/GetAllTemplatesFromNotify.java, src/main/java/uk/gov/hmcts/sptribs/notification/NotificationHelper.java, src/main/java/uk/gov/hmcts/sptribs/notification/NotificationServiceCIC.java, src/main/java/uk/gov/hmcts/sptribs/services/CaseManagementService.java, src/main/java/uk/gov/hmcts/sptribs/services/DocumentManagementService.java, src/main/java/uk/gov/hmcts/sptribs/systemupdate/convert/CaseDetailsListConverter.java, src/main/java/uk/gov/hmcts/sptribs/systemupdate/service/CcdSearchService.java, src/main/java/uk/gov/hmcts/sptribs/systemupdate/service/CcdUpdateService.java
Removed unwanted logging statements
https://tools.hmcts.net/jira/browse/DTSSTCI-899
=> DTSSTCI-899: Removed unwanted logging statements

src/integrationTest/java/uk/gov/hmcts/sptribs/common/notification/ApplicationReceivedNotificationIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/common/notification/CancelHearingNotificationIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/common/notification/CaseFinalDecisionIssuedNotificationIT.java
Create integration tests for:
- ApplicationReceivedNotification
- CancelHearingNotification
- CaseFinalDecisionIssuedNotification
https://tools.hmcts.net/jira/browse/DTSSTCI-966
=> DTSSTCI-966

src/integrationTest/java/uk/gov/hmcts/sptribs/common/notification/CaseIssuedNotificationIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/common/notification/CaseLinkedNotificationIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/common/notification/CaseReinstatedNotificationIT.java
Add integration tests for CaseIssuedNotification, CaseLinkedNotification and CaseReinstatedNotification.
https://tools.hmcts.net/jira/browse/DTSSTCI-967
=> DTSSTCI-967

src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WATaskRegisterNewCaseFT.java
Disable functional test
https://tools.hmcts.net/jira/browse/DTSSTCI-577
=> Disable WA functional test

src/integrationTest/java/uk/gov/hmcts/sptribs/common/notification/ApplicationReceivedNotificationIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/systemupdate/event/SystemMigrateCaseFlagsIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/systemupdate/event/SystemMigrateCaseLinksIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/systemupdate/event/SystemMigrateOldHearingIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/systemupdate/event/SystemTriggerStitchCollateHearingBundleIT.java, src/integrationTest/resources/responses/system-migrate-case-flags-about-to-submit-response.json, src/integrationTest/resources/responses/system-migrate-old-hearing-about-to-submit-response.json
Create integration tests for systemupdate event
https://tools.hmcts.net/jira/browse/DTSSTCI-950
=> DTSSTCI-950

src/integrationTest/java/uk/gov/hmcts/sptribs/common/notification/CaseWithdrawnNotificationIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/common/notification/ContactPartiesNotificationIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/common/notification/DecisionIssuedNotificationIT.java
Create tests for
- CaseWithdrawnNotification
- ContactPartiesNotification
- DecisionIssuedNotification
https://tools.hmcts.net/jira/browse/DTSSTCI-969
=> DTSSTCI-969

src/integrationTest/java/uk/gov/hmcts/sptribs/common/notification/CaseStayedNotificationIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/common/notification/CaseUnlinkedNotificationIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/common/notification/CaseUnstayedNotificationIT.java
Add integration tests for CaseStayedNotification, CaseUnlinkedNotification and CaseUnstayedNotification.
https://tools.hmcts.net/jira/browse/DTSSTCI-968
=> DTSSTCI-968

src/integrationTest/java/uk/gov/hmcts/sptribs/common/notification/ListingUpdatedNotificationIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/common/notification/NewOrderIssuedNotificationIT.java
Add integration tests for ListingUpdatedNotification and NewOrderIssuedNotification
https://tools.hmcts.net/jira/browse/DTSSTCI-971
=> DTSSTCI-971

src/integrationTest/java/uk/gov/hmcts/sptribs/systemupdate/service/CaseDetailsUpdaterIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/systemupdate/service/CcdSearchServiceIT.java, src/integrationTest/java/uk/gov/hmcts/sptribs/systemupdate/service/CcdUpdateServiceIT.java
Add integration tests for CaseDetailsUpdater, CcdUpdateService and CcdSearchService
https://tools.hmcts.net/jira/browse/DTSSTCI-951
=> DTSSTCI-951

src/integrationTest/java/uk/gov/hmcts/sptribs/notification/NotificationServiceCicIT.java, src/integrationTest/resources/responses/notification-response.json, src/main/java/uk/gov/hmcts/sptribs/notification/NotificationServiceCIC.java
Create integration tests for NotificationServiceCIC
https://tools.hmcts.net/jira/browse/DTSSTCI-957
=> DTSSTCI-957

src/integrationTest/java/uk/gov/hmcts/sptribs/common/service/SubmissionServiceIT.java
Add integration tests for SubmissionService
https://tools.hmcts.net/jira/browse/DTSSTCI-693
=> DTSSTCI-693

src/main/resources/dmn/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskWaPermissionTest.java
Remove own permission from task-supervisor
https://tools.hmcts.net/jira/browse/DTSSTCI-1152
=> DTSSTCI-1152

src/integrationTest/java/uk/gov/hmcts/sptribs/common/service/HearingServiceIT.java, src/test/java/uk/gov/hmcts/sptribs/testutil/TestDataHelper.java
Add integration tests for HearingService
https://tools.hmcts.net/jira/browse/DTSSTCI-972
=> DTSSTCI-972

src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessCorrectionsFT.java
Add integration test for ProcessCorrections
https://tools.hmcts.net/jira/browse/DTSSTCI-1114
=> DTSSTCI-1114

src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessTimeExtensionDirectionsReturnedFT.java
Add functional test for ProcessTimeExtensionDirectionsReturned task
https://tools.hmcts.net/jira/browse/DTSSTCI-1117
=> DTSSTCI-1117

src/cftlib/java/uk/gov/hmcts/sptribs/cftlib/CftLibConfig.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessCaseWithdrawalDirectionsFT.java, src/main/java/uk/gov/hmcts/sptribs/caseworker/model/CaseManagementLocation.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/CaseData.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/State.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/UserRole.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/UserRolesForAccessProfiles.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/access/CaseworkerRASValidationAccess.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/accessprofile/CICAccessProfile.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/search/SearchCriteria.java, src/main/java/uk/gov/hmcts/sptribs/common/ccd/HighLevelDataSetupApp.java, src/test/java/uk/gov/hmcts/sptribs/ciccase/model/access/CaseworkerRASValidationAccessTest.java
Add caseworker-ras-validation role needed for specific access
https://tools.hmcts.net/jira/browse/DTSSTCI-1067
=> DTSSTCI-1067

src/functionalTest/java/uk/gov/hmcts/sptribs/testutil/TaskManagementService.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WACompleteHearingOutcomeFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAIssueCaseToRespondentFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAIssueDecisionNoticeFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessCaseWithdrawalDirectionsFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessCorrectionsFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessDirectionsReListedCaseFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessDirectionsReturnedFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessFurtherEvidenceFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessListingDirectionsFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessOtherDirectionsReturnedFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessRule27DecisionFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessTimeExtensionDirectionsReturnedFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAStitchCollateHearingBundleFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WATaskRegisterNewCaseFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAVetNewCaseDocumentsFT.java
Add integration test for ProcessDirectionsReturned
https://tools.hmcts.net/jira/browse/DTSSTCI-1115
=> DTSSTCI-1115

build.gradle, src/functionalTest/java/uk/gov/hmcts/sptribs/testutil/TaskManagementService.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAFollowUpNoncomplianceOfDirectionsFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessDirectionsReListedCaseWithin5DaysFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessPostponementDirectionsFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessSetAsideDirectionsFT.java, src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAProcessStayDirectionsFT.java
Add functional test for ProcessStayDirections task
https://tools.hmcts.net/jira/browse/DTSSTCI-1121
=> DTSSTCI-1121

src/main/resources/dmn/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskWaConfigurationTest.java
Review and fix discrepancies with Task Due Dates
[DTSSTCI-1157](https://tools.hmcts.net/jira/browse/DTSSTCI-1157)
=> [DTSSTCI-1157] Update configuration DMN for task due dates

src/main/resources/dmn/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskWaConfigurationTest.java
Make process other dir returned task routine work
https://tools.hmcts.net/jira/browse/DTSSTCI-1163
=> DTSSTCI-1163

src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAReviewPostponementRequestJudgeFT.java
Add functional test for ReviewPostponementRequestJudge task
https://tools.hmcts.net/jira/browse/DTSSTCI-1136
=> DTSSTCI-1136

src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAReviewCorrectionsRequestFT.java
Add functional test for ReviewCorrectionsRequest task
https://tools.hmcts.net/jira/browse/DTSSTCI-1137
=> DTSSTCI-1137

src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAReviewReinstatementRequestJudgeFT.java
Add functional test for ReviewReinstatementRequestJudge task
https://tools.hmcts.net/jira/browse/DTSSTCI-1139
=> DTSSTCI-1139

src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAReviewStayRequestJudgeFT.java
Add functional test for ReviewStayRequestJudge task
https://tools.hmcts.net/jira/browse/DTSSTCI-1141
=> DTSSTCI-1141

src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAReviewNewCaseAndProvideDirectionsJudgeFT.java
Add functional test for ReviewNewCaseAndProvideDirectionsJudge task
https://tools.hmcts.net/jira/browse/DTSSTCI-1142
=> DTSSTCI-1142

src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAReviewOtherRequestJudgeFT.java
Add functional test for ReviewOtherRequestJudge task
https://tools.hmcts.net/jira/browse/DTSSTCI-1143
=> DTSSTCI-1143

src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAReviewRule27RequestJudgeFT.java
Add functional test for ReviewRule27RequestJudge task
https://tools.hmcts.net/jira/browse/DTSSTCI-1145
=> DTSSTCI-1145

src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAReviewListingDirectionsJudgeFT.java
Add functional test for ReviewListingDirectionsJudge task
https://tools.hmcts.net/jira/browse/DTSSTCI-1146
=> DTSSTCI-1146

src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAReviewListCaseJudgeFT.java
Add functional test for ReviewListCaseJudge task
https://tools.hmcts.net/jira/browse/DTSSTCI-1147
=> DTSSTCI-1147

src/functionalTest/java/uk/gov/hmcts/sptribs/wa/WAReviewStrikeOutRequestJudgeFT.java
Add functional test for ReviewStrikeOutRequestJudge task
https://tools.hmcts.net/jira/browse/DTSSTCI-1148
=> DTSSTCI-1148

src/main/resources/dmn/wa-task-permissions-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskWaPermissionTest.java
Update Regional Hearing Centre Team Leader to see specific access request for admins
https://tools.hmcts.net/jira/browse/DTSSTCI-1165
=> [DTSSTCI-1165] Regional Hearing Centre Team Lead should see access_requests task in available tasks tab

src/main/resources/dmn/privilege-calendar.json, src/main/resources/dmn/wa-task-configuration-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmnutils/CamundaTaskConstants.java
Add privilege day as non working day in dueDateNonWorkingCalendar
https://tools.hmcts.net/jira/browse/DTSSTCI-1162
=> DTSSTCI-1162

src/main/resources/dmn/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/main/resources/dmn/wa-task-types-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskTypesTest.java, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskWaInitiationTest.java
Specific Access tasks kept as is.
=> Update Task names to follow sentence case

src/main/resources/dmn/privilege-calendar.json, src/main/resources/dmn/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskCompletionTest.java
Update privilege calendar and make create-draft-order taskless
https://tools.hmcts.net/jira/browse/DTSSTCI-1227
=> DTSSTCI-1227

src/main/resources/dmn/wa-task-initiation-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskWaInitiationTest.java
Update SLAs for ReviewTimeExtensionRequestJudge and ReviewTimeExtensionRequestLO
https://tools.hmcts.net/jira/browse/DTSSTCI-1204
=> DTSSTCI-1204

src/main/resources/dmn/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskCompletionTest.java
Make caseworker-issue-final-decision event taskless
https://tools.hmcts.net/jira/browse/DTSSTCI-1234
=> DTSSTCI-1234

src/main/resources/dmn/wa-task-completion-st_cic-criminalinjuriescompensation.dmn, src/test/java/uk/gov/hmcts/sptribs/dmn/CamundaTaskCompletionTest.java
Make caseworker-issue-decision taskless
https://tools.hmcts.net/jira/browse/DTSSTCI-1235
=> DTSSTCI-1235

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/CaseworkerRecordListing.java
Add AwaitingOutcome as valid initial state for caseworker-record-listing event
https://tools.hmcts.net/jira/browse/DTSSTCI-1236
=> DTSSTCI-1236

build.gradle, charts/sptribs-case-api/Chart.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSSTCI-
=> Update suppressions.xml and update java version

build.gradle
https://tools.hmcts.net/jira/browse/DTSSTCI-
=> update fortify dependency naming

src/main/java/uk/gov/hmcts/sptribs/ciccase/model/State.java
Make sure the heading order is h1 to h2, rather than h1 to h3
https://tools.hmcts.net/jira/browse/DTSSTCI-1385
=> DTSSTCI-1385: Accessibility - Heading structure on case events

src/main/java/uk/gov/hmcts/sptribs/caseworker/event/page/AmendOrderDueDates.java, src/main/java/uk/gov/hmcts/sptribs/ciccase/model/State.java
Changing h2 back to h3, so that there are not duplicate h2 headings when there are pages which do introduce other h2 headings
https://tools.hmcts.net/jira/browse/DTSSTCI-1385
=> DTSSTCI-1385: Accessibility - Heading structure on case events (REVERTING)
